// MECH AMMO

//GameplayResourceDef
//{
	//id				"ammo_mech_advanced_weapons"
	//localization_id "resource_name/ammo_mech_advanced_weapons"
	//bp  			""
	//type 			"global"
	//specific_type 	"ammo"
	//icon			"gui/hud/resource_icons/ammo_mech_advanced_weapons_icon"
	//bigger_icon		"gui/hud/resource_icons/ammo_mech_advanced_weapons_icon_bigger"	
	//base_storage	"25"
	//production		"25"
	//hud_visible 	"never"
	//order			"20"
	
	//manufacture_cost "1"
//}

GameplayResourceDef
{
	id				"ammo_mech_medium_caliber"
	localization_id "resource_name/ammo_mech_medium_caliber"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_medium_caliber_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_medium_caliber_icon_bigger"	
	base_storage	"10.6"
	production		"10.6"
	hud_visible 	"never"
	order			"27"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_acid_cells"
	localization_id "resource_name/ammo_mech_acid_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_acid_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_acid_cells_icon_bigger"	
	base_storage	"12.5"
	production		"12.5"
	hud_visible 	"never"
	order			"28"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_cryo_cells"
	localization_id "resource_name/ammo_mech_cryo_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_cryo_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_cryo_cells_icon_bigger"	
	base_storage	"15.4"
	production		"15.4"
	hud_visible 	"never"
	order			"29"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_magma_cells"
	localization_id "resource_name/ammo_mech_magma_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_magma_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_magma_cells_icon_bigger"	
	base_storage	"14.4"
	production		"14.4"
	hud_visible 	"never"
	order			"30"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_plasma_cells"
	localization_id "resource_name/ammo_mech_plasma_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_plasma_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_plasma_cells_icon_bigger"	
	base_storage	"13.4"
	production		"13.4"
	hud_visible 	"never"
	order			"31"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_radio_cells"
	localization_id "resource_name/ammo_mech_radio_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_radio_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_radio_cells_icon_bigger"	
	base_storage	"10.5"
	production		"10.5"
	hud_visible 	"never"
	order			"32"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_gravity_matrix"
	localization_id "resource_name/ammo_mech_gravity_matrix"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_gravity_matrix_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_gravity_matrix_icon_bigger"	
	base_storage	"16.3"
	production		"16.3"
	hud_visible 	"never"
	order			"33"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_morphium_canister"
	localization_id "resource_name/ammo_mech_morphium_canister"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_morphium_canister_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_morphium_canister_icon_bigger"		
	base_storage	"11.5"
	production		"11.5"
	hud_visible 	"never"
	order			"34"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_rift_charge"
	localization_id "resource_name/ammo_mech_rift_charge"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_rift_charge_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_rift_charge_icon_bigger"	
	base_storage	"13"
	production		"13"
	hud_visible 	"never"
	order			"35"
	
	manufacture_cost "1"
}

// TOWER AMMO

GameplayResourceDef
{
	id				"ammo_tower_plasma_cells"
	localization_id "resource_name/ammo_tower_plasma_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_plasma_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_plasma_cells_icon_bigger"
	base_storage	"100"
	production		"20"
	hud_visible 	"build_menu"
	order			"20"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_advanced_explosive"
	localization_id "resource_name/ammo_tower_advanced_explosive"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_advanced_explosive_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_advanced_explosive_icon_bigger"
	base_storage	"100"
	production		"13"
	hud_visible 	"build_menu"
	order			"21"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_acid_cells"
	localization_id "resource_name/ammo_tower_acid_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_acid_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_acid_cells_icon_bigger"
	base_storage	"100"
	production		"12"
	hud_visible 	"build_menu"
	order			"22"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_cryo_cells"
	localization_id "resource_name/ammo_tower_cryo_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_cryo_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_cryo_cells_icon_bigger"
	base_storage	"100"
	production		"15"
	hud_visible 	"build_menu"
	order			"23"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_magma_cells"
	localization_id "resource_name/ammo_tower_magma_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_magma_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_magma_cells_icon_bigger"
	base_storage	"100"
	production		"14"
	hud_visible 	"build_menu"
	order			"24"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_radio_cells"
	localization_id "resource_name/ammo_tower_radio_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_radio_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_radio_cells_icon_bigger"
	base_storage	"100"
	production		"9"
	hud_visible 	"build_menu"
	order			"25"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_gravity_matrix"
	localization_id "resource_name/ammo_tower_gravity_matrix"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_gravity_matrix_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_gravity_matrix_icon_bigger"
	base_storage	"100"
	production		"18"
	hud_visible 	"build_menu"
	order			"26"
	
	
	manufacture_cost "1"
}