GameplayResourceDef
{
	id				"ammo_mech_advanced_weapons"
	localization_id "resource_name/ammo_mech_advanced_weapons"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_advanced_weapons_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_advanced_weapons_icon_bigger"	
	base_storage	"30"
	production		"30"
	hud_visible 	"never"
	order			"20"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_plasma_cells"
	localization_id "resource_name/ammo_tower_plasma_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_plasma_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_plasma_cells_icon_bigger"
	base_storage	"375"
	production		"75"
	hud_visible 	"build_menu"
	order			"13"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_guided"
	localization_id "resource_name/ammo_tower_guided"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_guided_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_guided_icon_bigger"
	base_storage	"50"
	production		"10"
	hud_visible 	"build_menu"
	order			"14"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_acid_cells"
	localization_id "resource_name/ammo_tower_acid_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_acid_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_acid_cells_icon_bigger"
	base_storage	"375"
	production		"75"
	hud_visible 	"build_menu"
	order			"15"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_cryo_cells"
	localization_id "resource_name/ammo_tower_cryo_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_cryo_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_cryo_cells_icon_bigger"
	base_storage	"375"
	production		"75"
	hud_visible 	"build_menu"
	order			"16"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_magma_cells"
	localization_id "resource_name/ammo_tower_magma_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_magma_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_magma_cells_icon_bigger"
	base_storage	"375"
	production		"75"
	hud_visible 	"build_menu"
	order			"17"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_radio_cells"
	localization_id "resource_name/ammo_tower_radio_cells"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_radio_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_radio_cells_icon_bigger"
	base_storage	"375"
	production		"75"
	hud_visible 	"build_menu"
	order			"18"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_gravity"
	localization_id "resource_name/ammo_tower_gravity"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_tower_gravity_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_gravity_icon_bigger"
	base_storage	"375"
	production		"75"
	hud_visible 	"build_menu"
	order			"19"
	
	
	manufacture_cost "1"
}