//----------------------EXPANDED ARSENAL MOD START----------------------\\

// MECH CONSUMABLE MANUFACTORING MULTIPLIERS

GameplayResourceDef
{
	id				"player_consumables_manufacturing_acid"
	localization_id "resource_name/player_consumables_manufacturing_acid"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_consumables_manufacturing_crystal"
	localization_id "resource_name/player_consumables_manufacturing_crystal"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}


GameplayResourceDef
{
	id				"player_consumables_manufacturing_cryo"
	localization_id "resource_name/player_consumables_manufacturing_cryo"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_consumables_manufacturing_magma"
	localization_id "resource_name/player_consumables_manufacturing_magma"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_consumables_manufacturing_plasma"
	localization_id "resource_name/player_consumables_manufacturing_plasma"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_consumables_manufacturing_radio"
	localization_id "resource_name/player_consumables_manufacturing_radio"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_consumables_manufacturing_gravity"
	localization_id "resource_name/player_consumables_manufacturing_gravity"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_consumables_manufacturing_morphium"
	localization_id "resource_name/player_consumables_manufacturing_morphium"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_consumables_manufacturing_rift"
	localization_id "resource_name/player_consumables_manufacturing_rift"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_consumables_manufacturing_explosive"
	localization_id "resource_name/player_consumables_manufacturing_explosive"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

// MECH AMMO MANUFACTORING MULTIPLIERS

GameplayResourceDef
{
	id				"player_ammo_manufacturing_medium_caliber"
	localization_id "resource_name/player_ammo_manufacturing_medium_caliber"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_ammo_manufacturing_acid_cells"
	localization_id "resource_name/player_ammo_manufacturing_acid_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_ammo_manufacturing_cryo_cells"
	localization_id "resource_name/player_ammo_manufacturing_cryo_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_ammo_manufacturing_magma_cells"
	localization_id "resource_name/player_ammo_manufacturing_magma_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_ammo_manufacturing_plasma_cells"
	localization_id "resource_name/player_ammo_manufacturing_plasma_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_ammo_manufacturing_radio_cells"
	localization_id "resource_name/player_ammo_manufacturing_radio_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_ammo_manufacturing_gravity_matrix"
	localization_id "resource_name/player_ammo_manufacturing_gravity_matrix"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_ammo_manufacturing_morphium_canister"
	localization_id "resource_name/player_ammo_manufacturing_morphium_canister"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"player_ammo_manufacturing_rift_charge"
	localization_id "resource_name/player_ammo_manufacturing_rift_charge"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

// TOWER MANUFACTORING MULTIPLIERS

GameplayResourceDef
{
	id				"ammo_manufacturing_plasma_cells"
	localization_id "resource_name/ammo_manufacturing_plasma_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_advanced_explosive"
	localization_id "resource_name/ammo_manufacturing_advanced_explosive"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_acid_cells"
	localization_id "resource_name/ammo_manufacturing_acid_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_cryo_cells"
	localization_id "resource_name/ammo_manufacturing_cryo_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_magma_cells"
	localization_id "resource_name/ammo_manufacturing_magma_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_radio_cells"
	localization_id "resource_name/ammo_manufacturing_radio_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_gravity_matrix"
	localization_id "resource_name/ammo_manufacturing_gravity_matrix"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

//----------------------EXPANDED ARSENAL MOD END----------------------\\
