//----------------------EXPANDED ARSENAL MOD START----------------------\\

GameplayResourceDef
{
	id				"advanced_consumables_manufacturing"
	localization_id "resource_name/advanced_consumables_manufacturing"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_advanced_weapons"
	localization_id "resource_name/ammo_manufacturing_advanced_weapons"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_plasma_cells"
	localization_id "resource_name/ammo_manufacturing_plasma_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_guided"
	localization_id "resource_name/ammo_manufacturing_guided"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_acid_cells"
	localization_id "resource_name/ammo_manufacturing_acid_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_cryo_cells"
	localization_id "resource_name/ammo_manufacturing_cryo_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_magma_cells"
	localization_id "resource_name/ammo_manufacturing_magma_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_radio_cells"
	localization_id "resource_name/ammo_manufacturing_radio_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_gravity"
	localization_id "resource_name/ammo_manufacturing_gravity"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
}

//----------------------EXPANDED ARSENAL MOD END----------------------\\
