RegisterGlobalEventHandler("PlayerCreatedEvent", function(evt)
    
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_01")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_02")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_03")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_04")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_05")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_06")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_07")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_08")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_09")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_10")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_11")

    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_01")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_02")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_03")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_04")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_05")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_06")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_07")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_08")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_09")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_10")
    BuildingService:UnlockBuilding("buildings/tools/buildings_builder_11")
end)

