RegisterGlobalEventHandler("PlayerCreatedEvent", function(evt)
    
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_01")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_02")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_03")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_04")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_05")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_06")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_07")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_08")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_09")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_10")
    BuildingService:UnlockBuilding("buildings/tools/buildings_picker_11")

    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_01")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_02")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_03")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_04")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_05")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_06")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_07")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_08")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_09")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_10")
    BuildingService:UnlockBuilding("buildings/tools/buildings_saver_11")
end)

