,melee_weapon,range_weapon,movement,aiming,interactive,consumable,skill,shield,move_dir,dash_skill,equipment,enemy_range_weapon,barrier,movement_skill,lift
melee_weapon,melee_weapon|BLOCK,melee_weapon|INTERRUPT,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,melee_weapon|INTERRUPT,|ALL,|ALL,|BLOCK,melee_weapon|INTERRUPT,|ALL,melee_weapon|INTERRUPT,melee_weapon|INTERRUPT_AND_BLOCK
range_weapon,melee_weapon|INTERRUPT,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,skill|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,range_weapon|INTERRUPT,range_weapon|INTERRUPT_AND_BLOCK
movement,|ALL,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
aiming,|ALL,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
interactive,interactive|INTERRUPT,interactive|INTERRUPT,interactive|INTERRUPT,interactive|INTERRUPT,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,interactive|INTERRUPT,interactive|INTERRUPT,interactive|INTERRUPT,|ALL,interactive|INTERRUPT,lift|INTERRUPT
consumable,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,movement_skill|INTERRUPT,|ALL
skill,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,movement_skill|INTERRUPT,|ALL
shield,melee_weapon|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
move_dir,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
dash_skill,|ALL,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|BLOCK,|BLOCK
equipment,|BLOCK,|BLOCK,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|BLOCK,|ALL,|ALL,|ALL,|ALL
enemy_range_weapon,melee_weapon|INTERRUPT,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
barrier,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
movement_skill,melee_weapon|INTERRUPT,range_weapon|INTERRUPT,|ALL,|ALL,interactive|INTERRUPT,movement_skill|INTERRUPT,movement_skill|INTERRUPT,|ALL,|ALL,|BLOCK,|ALL,|ALL,|ALL,|ALL,|BLOCK
lift,melee_weapon|INTERRUPT_AND_BLOCK,range_weapon|INTERRUPT_AND_BLOCK,|ALL,|ALL,lift|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|BLOCK,|ALL,|ALL,|ALL,|BLOCK,|BLOCK
