,melee_weapon,range_weapon,movement,aiming,interactive,consumable,skill,shield,move_dir,dash_skill,equipment,enemy_range_weapon,barrier,movement_skill,lift,special,invisible_skill
melee_weapon,melee_weapon|BLOCK,melee_weapon|INTERRUPT,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,melee_weapon|INTERRUPT,|ALL,|ALL,|BLOCK,melee_weapon|INTERRUPT,|ALL,movement_skill|INTERRUPT,melee_weapon|INTERRUPT_AND_BLOCK,|ALL,melee_weapon|INTERRUPT
range_weapon,melee_weapon|INTERRUPT,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,skill|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,movement_skill|INTERRUPT,range_weapon|INTERRUPT_AND_BLOCK,|ALL,range_weapon|INTERRUPT
movement,|ALL,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
aiming,|ALL,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
interactive,interactive|INTERRUPT,interactive|INTERRUPT,interactive|INTERRUPT,interactive|INTERRUPT,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,interactive|INTERRUPT,interactive|INTERRUPT,interactive|INTERRUPT,|ALL,|BLOCK,lift|INTERRUPT,|ALL,interactive|INTERRUPT
consumable,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,movement_skill|INTERRUPT,|ALL,|ALL,movement_skill|INTERRUPT
skill,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,movement_skill|INTERRUPT,|ALL,|ALL,movement_skill|INTERRUPT
shield,melee_weapon|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
move_dir,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
dash_skill,|ALL,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|BLOCK,|BLOCK,|ALL,|BLOCK
equipment,|BLOCK,|BLOCK,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|BLOCK,|ALL,|ALL,movement_skill|INTERRUPT,|ALL,|ALL,|ALL
enemy_range_weapon,melee_weapon|INTERRUPT,|ALL,|ALL,|ALL,interactive|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
barrier,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
movement_skill,movement_skill|INTERRUPT,movement_skill|INTERRUPT,|ALL,|ALL,|BLOCK,movement_skill|INTERRUPT,movement_skill|INTERRUPT,|ALL,|ALL,|BLOCK,movement_skill|INTERRUPT,|ALL,|ALL,|ALL,|BLOCK,|ALL,|ALL
lift,melee_weapon|INTERRUPT_AND_BLOCK,range_weapon|INTERRUPT_AND_BLOCK,|ALL,|ALL,lift|INTERRUPT,|ALL,|ALL,|ALL,|ALL,|BLOCK,|ALL,|ALL,|ALL,|BLOCK,|BLOCK,|ALL,|BLOCK
special,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL,|ALL
invisible_skill,melee_weapon|INTERRUPT,range_weapon|INTERRUPT,|ALL,|ALL,interactive|INTERRUPT,movement_skill|INTERRUPT,movement_skill|INTERRUPT,|ALL,|ALL,|BLOCK,|ALL,|ALL,|ALL,|ALL,|BLOCK,|ALL,|ALL
