GameplayResourceDef
{
	id				"ammo_mech_low_caliber"
	localization_id "resource_name/ammo_mech_low_caliber"
	bp  			""
	type 			"ammo_mech"
	icon			"gui/hud/resource_icons/ammo_mech_low_caliber_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_low_caliber_icon_bigger"
	base_storage	"80"
	production		"80"
	hud_visible 	"never"
	order			"15"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_high_caliber"
	localization_id "resource_name/ammo_mech_high_caliber"
	bp  			""
	type 			"ammo_mech"
	icon			"gui/hud/resource_icons/ammo_mech_high_caliber_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_high_caliber_icon_bigger"
	base_storage	"30"
	production		"30"
	hud_visible 	"never"
	order			"16"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_liquid"
	localization_id "resource_name/ammo_mech_liquid"
	bp  			""
	type 			"ammo_mech"
	icon			"gui/hud/resource_icons/ammo_mech_liquid_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_liquid_icon_bigger"
	base_storage	"250"
	production		"250"
	hud_visible 	"never"
	order			"18"
		
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_explosive"
	localization_id "resource_name/ammo_mech_explosive"
	bp  			""
	type 			"ammo_mech"
	icon			"gui/hud/resource_icons/ammo_mech_explosive_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_explosive_icon_bigger"	
	base_storage	"3"
	production		"3"
	hud_visible 	"never"
	order			"17"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_energy_cell"
	localization_id "resource_name/ammo_mech_energy"
	bp  			""
	type 			"ammo_mech"
	icon			"gui/hud/resource_icons/ammo_mech_energy_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_energy_icon_bigger"	
	base_storage	"20"
	production		"20"
	hud_visible 	"never"
	order			"19"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_liquid"
	localization_id "resource_name/ammo_tower_liquid"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_liquid_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_liquid_icon_bigger"
	base_storage	"2000"
	production		"250"
	hud_visible 	"build_menu"
	order			"14"
	
		
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_explosive"
	localization_id "resource_name/ammo_tower_explosive"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_explosive_icon"	
	bigger_icon		"gui/hud/resource_icons/ammo_tower_explosive_icon_bigger"	
	base_storage	"30"
	production		"6"
	hud_visible 	"build_menu"
	order			"13"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_low_caliber"
	localization_id "resource_name/ammo_tower_low_caliber"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_low_caliber_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_low_caliber_icon_bigger"
	base_storage	"1000"
	production		"200"
	hud_visible 	"build_menu"
	order			"11"
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_high_caliber"
	localization_id "resource_name/ammo_tower_high_caliber"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_high_caliber_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_high_caliber_icon_bigger"
	base_storage	"300"
	production		"60"
	hud_visible 	"build_menu"
	order			"12"
		
	manufacture_cost "1"
}