GameplayResourceDef
{
	id				"cosmic_biomass_plant"
	localization_id "resource_name/cosmic_biomas_plant"
	bp  			"items/loot/resources/cosmic_biomass_plant_item"
	type 			"loot"
	icon			"gui/hud/resource_icons/cosmic_biomass_plant"
	bigger_icon		"gui/hud/resource_icons/cosmic_biomass_plant_bigger"
	hud_visible 	"build_menu"
	allow_overflow 	"1"
	missing_effect "voice_over/announcement/not_enough_plant_biomass"
	order   		"9"		
}

