//----------------------TOWER ARSENAL MOD START----------------------\\

GameplayResourceDef
{
	id				"ammo_manufacturing_cryogenic_cells"
	localization_id "resource_name/ammo_manufacturing_cryogenic_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_tower_cryogenic_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_cryogenic_cells_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_acidic_cells"
	localization_id "resource_name/ammo_manufacturing_acidic_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_tower_acidic_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_acidic_cells_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_flame_cells"
	localization_id "resource_name/ammo_manufacturing_flame_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_tower_flame_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_flame_cells_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_cosmic_cells"
	localization_id "resource_name/ammo_manufacturing_cosmic_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_tower_cosmic_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_cosmic_cells_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_manufacturing_plasmoid_cells"
	localization_id "resource_name/ammo_manufacturing_plasmoid_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_tower_plasmoid_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_plasmoid_cells_icon_bigger"
	allow_overflow 	"1"
}

//GameplayResourceDef
//{
//	id				"ammo_manufacturing_cells"
//	localization_id "resource_name/ammo_manufacturing_cells"
//	bp  			""
//	type 			"manufacturing"
//	icon			"gui/hud/resource_icons/ammo_icon"
//	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
//	allow_overflow 	"1"
//	order   		"38"
//}

//													
//---------------- MECH AMMO ---------------------\\
//													

GameplayResourceDef
{
	id				"ammo_cosmic_cells"
	localization_id "resource_name/ammo_cosmic_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
	order   		"39"
}

GameplayResourceDef
{
	id				"ammo_mech_cosmic_machinegun_cells"
	localization_id "resource_name/ammo_mech_cosmic_machinegun_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"ammo_plasmoid_cells"
	localization_id "resource_name/ammo_mech_plasmoid_cells"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
	order   		"40"
}

GameplayResourceDef
{
	id				"ammo_mech_cosmic_explosive"
	localization_id "resource_name/ammo_mech_cosmic_explosive"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
	order   		"41"
}
//----------------------TOWER ARSENAL MOD END----------------------\\
