mod_picker_tool_extension_heal_neutral_tool = 1

mod_picker_tool_extension_spawner_activate_tool = 1

mod_picker_tool_extension_eraser_wrecks_tool = 1

mod_picker_tool_extension_eraser_mines_tool = 1

mod_picker_tool_extension_eraser_rocks_tool = 1

mod_picker_tool_extension_loot_collecting_tool = 1

mod_picker_tool_extension_ruins_eraser_tool = 1
