GameplayResourceDef
{
	id				"consumables_manufacturing"
	localization_id "resource_name/consumables_manufacturing"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/consumable_icon"
	bigger_icon		"gui/hud/resource_icons/consumable_icon_bigger"
	allow_overflow 	"1"
	order   		"30"
}

GameplayResourceDef
{
	id				"ammo_manufacturing"
	localization_id "resource_name/ammo_manufacturing"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/ammo_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_icon_bigger"
	allow_overflow 	"1"
	order   		"31"
}


GameplayResourceDef
{
	id				"player_ammo_manufacturing"
	localization_id "resource_name/player_ammo_manufacturing"
	bp  			""
	type 			"manufacturing"
	icon			"gui/hud/resource_icons/player_ammo_icon"
	bigger_icon		"gui/hud/resource_icons/player_ammo_icon_bigger"
	allow_overflow 	"1"
	order   		"32"
}

