system rift/plasmoid_rifle_hit_small
{
    fixed_timeout                               0.2
    nonvisible_update_timeout                   1
    scale_velocity                              0.0075
    scale                                       0.0075 0.0075 0.0075
    tight_bounding_box                          true
    cache_count                                 200
    technique lines
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/muzzle_flash_plasmoid_2x2
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               45
            time_to_live                        0.2
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      40
            particle_height                     dyn_random
            {
                min                             200
                max                             275
            }
            end_texture_coords_range            3
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.3 0.3 0.3 0.9
            time_colour                         1    0 0 0 0
        }
    }
    technique flash2
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/muzzle_flash_plasmoid_2x2
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 2
            texture_coords_columns              2
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.2
            velocity                            0
            all_particle_dimensions             150
            direction                           1 0 0
            end_texture_coords_range            3
            colour                              0.501961 0.501961 0.501961 0.501961
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.9 0.9 0.9 0.9
            time_colour                         1    0 0 0 0
        }
    }
}
