system rift/cryo_shield_aura
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.01
    scale                                       0.01 0.01 0.01
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    technique sparks
    {
        visual_particle_quota                   40
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks
        {
            emission_rate                       40
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             3
                max                             4
            }
            all_particle_dimensions             dyn_random
            {
                min                             4
                max                             8
            }
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           200
            box_height                          200
            box_depth                           200
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.606522  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce Affector2525
        {
            force_vector                        0 150 0
        }
    }
}
