system rift/anoryxian_dig_down
{
    fixed_timeout                               10
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.03
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 2
    technique smoke1
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       150
            angle                               45
            time_to_live                        dyn_random
            {
                min                             1.4
                max                             1.8
            }
            velocity                            dyn_random
            {
                min                             200
                max                             300
            }
            duration                            7
            all_particle_dimensions             dyn_random
            {
                min                             150
                max                             200
            }
            position                            0 5 0
            box_width                           500
            box_height                          500
            box_depth                           500
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0.6 0.47451 0.384314 0
            time_colour                         0.13913  0.6 0.47451 0.384314 0.4
            time_colour                         0.706522  0.6 0.47451 0.384314 0.4
            time_colour                         1    0.6 0.47451 0.384314 0
        }
        affector                                TextureRotator Affector6
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             0.5
                max                             -0.5
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
        affector                                LinearForce Affector223
        {
            force_vector                        0 -300 0
        }
        affector                                Scale Affector233
        {
            xyz_scale                           50
        }
    }
    technique smoke_up
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       150
            angle                               5
            time_to_live                        dyn_random
            {
                min                             1.4
                max                             1.8
            }
            velocity                            dyn_random
            {
                min                             300
                max                             400
            }
            duration                            7
            all_particle_dimensions             dyn_random
            {
                min                             150
                max                             200
            }
            position                            0 5 0
            box_width                           500
            box_height                          500
            box_depth                           500
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0.6 0.47451 0.384314 0
            time_colour                         0.13913  0.6 0.47451 0.384314 0.4
            time_colour                         0.706522  0.6 0.47451 0.384314 0.4
            time_colour                         1    0.6 0.47451 0.384314 0
        }
        affector                                TextureRotator Affector6
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             0.5
                max                             -0.5
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
        affector                                LinearForce Affector223
        {
            force_vector                        0 -300 0
        }
        affector                                Scale Affector233
        {
            xyz_scale                           50
        }
    }
    technique smoke_dirt
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_explosion_dirt
        renderer                                Billboard
        {
            render_queue_group                  62
        }
        emitter                                 Box Emitter1
        {
            emission_rate                       150
            angle                               45
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             300
                max                             400
            }
            duration                            7
            all_particle_dimensions             dyn_random
            {
                min                             100
                max                             150
            }
            colour                              1 0.501961 0 1
            box_width                           500
            box_height                          500
            box_depth                           500
        }
        affector                                Colour Affector35
        {
            time_colour                         0    0.6 0.47451 0.384314 0
            time_colour                         0.13913  0.6 0.47451 0.384314 0.4
            time_colour                         0.706522  0.6 0.47451 0.384314 0.4
            time_colour                         1    0.6 0.47451 0.384314 0
        }
        affector                                LinearForce Affector22
        {
            force_vector                        0 -500 0
        }
    }
    technique rocks
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       150
            angle                               60
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             500
                max                             600
            }
            duration                            7
            all_particle_dimensions             dyn_random
            {
                min                             15
                max                             30
            }
            end_texture_coords_range            15
            start_colour_range                  0.501961 0.501961 0.501961 1
            end_colour_range                    0.313726 0.313726 0.313726 1
            box_width                           500
            box_height                          500
            box_depth                           500
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -800 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector18
        {
            time_colour                         0    0.6 0.47451 0.384314 0
            time_colour                         0.13913  0.6 0.47451 0.384314 0.4
            time_colour                         0.706522  0.6 0.47451 0.384314 0.4
            time_colour                         1    0.6 0.47451 0.384314 0
        }
    }
}
