system rift/anoryxian_arm_cannon_muzzle
{
    fixed_timeout                               3.5
    nonvisible_update_timeout                   1
    scale_velocity                              0.04
    scale                                       0.04 0.04 0.04
    tight_bounding_box                          true
    cache_count                                 8
    technique smoke
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box smoke_ring
        {
            emission_rate                       100
            angle                               25
            time_to_live                        dyn_random
            {
                min                             1.2
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             100
                max                             150
            }
            duration                            2
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             40
            }
            direction                           1 0 0
            auto_direction                      true
            box_width                           10
            box_height                          10
            box_depth                           10
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0 1 0
            time_colour                         0.5  0.501961 0 1 0.109804
            time_colour                         1    0.501961 0 1 0
        }
        affector                                TextureAnimator Affector25
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Scale Affector62
        {
            xyz_scale                           30
        }
        affector                                LinearForce Affector430
        {
            force_vector                        0 150 0
        }
    }
    technique smoke_ring
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box smoke_ring
        {
            emission_rate                       100
            angle                               15
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             100
                max                             500
            }
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             100
            }
            direction                           1 0 0
            auto_direction                      true
            force_emission                      true
            box_width                           50
            box_height                          50
            box_depth                           50
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0 1 0
            time_colour                         0.5  0.501961 0 1 0.298039
            time_colour                         1    0.501961 0 1 0
        }
        affector                                TextureAnimator Affector25
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Scale Affector62
        {
            xyz_scale                           5
        }
    }
    technique sparks_flashy
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_violet_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       800
            angle                               15
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             50
                max                             500
            }
            all_particle_dimensions             dyn_random
            {
                min                             4
                max                             8
            }
            direction                           1 0 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            auto_direction                      true
            force_emission                      true
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0.2 0.2 0.2 0
            time_colour                         0.25  1 1 1 0.709804
            time_colour                         0.408696  1 1 1 0.494118
            time_colour                         1    0.2 0.2 0.2 0
        }
        affector                                TextureRotator Affector6
        {
            rotation                            dyn_random
            {
                min                             -0.5
                max                             0.5
            }
            rotation_speed                      1
        }
    }
    technique refract_shockwave
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_rotation_type             vertex
        }
        emitter                                 Point flash2
        {
            emission_rate                       100
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.4
            }
            velocity                            0
            all_particle_dimensions             10
            keep_local                          true
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           500
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique flash
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_nodepth_02
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_rotation_type             vertex
        }
        emitter                                 Point flash2
        {
            emission_rate                       100
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.6
            }
            velocity                            0
            all_particle_dimensions             10
            keep_local                          true
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           300
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0 1 1
            time_colour                         0.904348  0.501961 0 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique debris
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_violet_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       100
            angle                               30
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            velocity                            dyn_random
            {
                min                             200
                max                             1000
            }
            particle_width                      dyn_random
            {
                min                             2
                max                             3
            }
            particle_height                     dyn_random
            {
                min                             6
                max                             9
            }
            direction                           1 0 0
            force_emission                      true
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -500 0
        }
        affector                                Colour Affector358
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
    }
}
