system rift/arachnoid_boss_melee_attack_start
{
    fixed_timeout                               5
    nonvisible_update_timeout                   1
    scale_velocity                              0.007
    scale                                       0.007 0.007 0.007
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 5
    technique smoke
    {
        enabled                                 false
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       50
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             0
                max                             50
            }
            duration                            1
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             100
            }
            radius                              25
        }
        affector                                Colour 
        {
            time_colour                         0    0.6 0.576471 0.4 0
            time_colour                         0.2  0.6 0.576471 0.4 0.2
            time_colour                         0.8  0.6 0.576471 0.4 0.2
            time_colour                         1    0.6 0.576471 0.4 0
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
    technique flash
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  66
        }
        emitter                                 Point Emitter7
        {
            time_to_live                        0.2
            velocity                            0
            all_particle_dimensions             500
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector19
        {
            xyz_scale                           4000
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 0 1
            time_colour                         1    0 0 0 0
        }
    }
    technique trail
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       100
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             1
            }
            velocity                            dyn_random
            {
                min                             0
                max                             50
            }
            duration                            0.9
            all_particle_dimensions             100
        }
        affector                                Colour 
        {
            time_colour                         0    0.176471 0 0 1
            time_colour                         1    0 0 0 0
        }
    }
    technique refract
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             100
            position                            0 50 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1499
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
        }
    }
}
