system rift/arcology_workshop_arm_tip
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.012
    scale                                       0.012 0.012 0.012
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 15
    technique lightning_directional_1
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_atlas_02_orange
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    top_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point add_flame_blue
        {
            emission_rate                       dyn_curved_linear
            {
                control_point                   0 4
                control_point                   3 40
            }
            angle                               0
            time_to_live                        0.2
            velocity                            0.1
            particle_width                      100
            particle_height                     100
            keep_local                          true
            direction                           1 0 0
            end_texture_coords_range            3
            colour                              0 1 1 1
        }
        affector                                TextureRotator Affector168
        {
            use_own_rotation                    true
            rotation                            -3.13
            rotation_speed                      0
        }
        affector                                Colour Affector197
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
        affector                                Scale Affector9
        {
            x_scale                             250
            y_scale                             250
        }
    }
    technique flare
    {
        keep_local                              true
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_02
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       30
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.6
            }
            velocity                            1
            all_particle_dimensions             dyn_random
            {
                min                             120
                max                             240
            }
            colour                              0.262745 0.937255 0.870588 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.508696  1 0.491103 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
    }
}
