system rift/aura_healing
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.01
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 5
    technique flash2
    {
        enabled                                 false
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/shockwave_02_add
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            emission_rate                       0.5
            time_to_live                        1
            velocity                            0
            all_particle_dimensions             1
            colour                              0.776471 0.388235 0 1
        }
        affector                                Scale flash2
        {
            xyz_scale                           500
        }
        affector                                Colour 
        {
            time_colour                         0    0 1 0 0.894118
            time_colour                         1    0 0 0 0
        }
        affector                                GeometryRotator Affector5
        {
            use_own_rotation                    true
            rotation_speed                      dyn_random
            {
                min                             -3
                max                             3
            }
        }
    }
    technique sparks
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/health_sign_add_01
        renderer                                Billboard
        {
            render_queue_group                  65
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 SphereSurface flash2
        {
            emission_rate                       100
            angle                               1
            time_to_live                        1
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            all_particle_dimensions             dyn_random
            {
                min                             5
                max                             15
            }
            colour                              0.776471 0.388235 0 1
            auto_direction                      true
            radius                              30
        }
        affector                                Colour 
        {
            time_colour                         0    0 1 0 1
            time_colour                         0.502174  0 1 0 1
            time_colour                         1    0 0 0 0
        }
    }
}
