system player/blue/blue_bomb_target_marker
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.0300
    scale                                       0.0300 0.0300 0.0300
    tight_bounding_box                          true
    cache_count                                 2	
    category                                    SHOOTER
    technique pillar
    {
        position                                0 10 0
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_explosion_01
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_type                      oriented_common
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
            common_direction                    0 1 0
        }
        emitter                                 Point 
        {
            emission_rate                       3
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.3
            }
            particle_width                      dyn_random
            {
                min                             10
                max                             20
            }
            particle_height                     dyn_random
            {
                min                             350
                max                             400
            }
            position                            0 50 0
            direction                           0 0 0
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.247826  1 1 1 1
            time_colour                         0.5  1 1 1 1
            time_colour                         0.754348  1 1 1 1
            time_colour                         1    1 1 1 0
        }
    }
    technique ring_radius1
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/alien_marker_ring_01
        renderer                                Billboard
        {
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            emission_rate                       40
            angle                               0
            time_to_live                        360
            velocity                            0.0001
            all_particle_dimensions             180
            colour                              0.188235 0.188235 0.188235 1
        }
        affector                                TextureRotator Affector226
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             -1
            }
        }
    }
    technique falling_sparks
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Box Emitter7
        {
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            position                            0 325 0
            direction                           0 -1 0
            colour                              1 0.501961 0 1
            box_width                           8
            box_height                          200
            box_depth                           8
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.206522  1 1 1 1
            time_colour                         0.804348  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             1
                max                             2
            }
        }
    }
}
