system player/blue/blue_spaceship_ghost
{
    scale_velocity                              0.0100
    scale                                       0.0100 0.0100 0.0100
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 2
    technique sparks_gravity
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 SphereSurface DebrisEmitter
        {
            emission_rate                       25
            angle                               85
            time_to_live                        2
            velocity                            dyn_random
            {
                min                             100
                max                             150
            }
            particle_width                      7
            particle_height                     dyn_random
            {
                min                             10
                max                             20
            }
            keep_local                          true
            start_colour_range                  1 1 1 1
            radius                              250
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 0.309804
            time_colour                         0.506522  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
        affector                                Gravity Affector70
        {
            mass_affector                       30000
            gravity                             5
        }
    }
    technique sparks_gravity_follow
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 SphereSurface DebrisEmitter
        {
            emission_rate                       50
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.9
                max                             1.1
            }
            velocity                            dyn_random
            {
                min                             100
                max                             150
            }
            particle_width                      7
            particle_height                     dyn_random
            {
                min                             10
                max                             20
            }
            start_colour_range                  1 1 1 1
            radius                              250
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 0.309804
            time_colour                         0.51087  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
        affector                                Gravity Affector70
        {
            mass_affector                       30000
            gravity                             5
        }
    }
}
