system player/blue/blue_bomb_core_lvl1
{
    scale_velocity                              0.0125
    scale                                       0.0125 0.0125 0.0125
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 2
    technique swirl4
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_01
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       20
            angle                               359
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             dyn_random
            {
                min                             225
                max                             275
            }
            keep_local                          true
            colour                              0.262745 0.937255 0.870588 1
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 0
            time_colour                         0.508696  0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             1
                max                             2
            }
        }
    }
    technique swirl3
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_02
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       20
            angle                               359
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             dyn_random
            {
                min                             170
                max                             220
            }
            keep_local                          true
            colour                              0.262745 0.937255 0.870588 1
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 0
            time_colour                         0.506522  0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -1
                max                             -2
            }
        }
    }
    technique swirl
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_01
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       20
            angle                               359
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             120
            keep_local                          true
            colour                              0.262745 0.937255 0.870588 1
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 0
            time_colour                         0.502174  0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             1
                max                             2
            }
        }
    }
    technique sparks_gravity
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 SphereSurface DebrisEmitter
        {
            emission_rate                       15
            angle                               85
            time_to_live                        2
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      5
            particle_height                     dyn_random
            {
                min                             5
                max                             20
            }
            keep_local                          true
            start_colour_range                  1 1 1 1
            radius                              80
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0.309804
            time_colour                         0.66087  1 1 1 0.298039
            time_colour                         1    1 1 1 0
        }
        affector                                Gravity Affector70
        {
            mass_affector                       10000
            gravity                             5
        }
    }
    technique core
    {
        visual_particle_quota                   3
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  66
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       3
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             1
            keep_local                          true
            colour                              0.262745 0.937255 0.870588 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -5
                max                             5
            }
        }
        affector                                Scale Affector76
        {
            xyz_scale                           dyn_random
            {
                min                             90
                max                             180
            }
        }
    }
}
