system rift/blue_hail
{
    nonvisible_update_timeout                   1
    disable_culling                             true
    scale_velocity                              0.025
    scale                                       0.025 0.025 0.025
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    technique 
    {
        visual_particle_quota                   1500
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_plasma_hit_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       1500
            angle                               3
            time_to_live                        1
            velocity                            2500
            particle_width                      dyn_random
            {
                min                             15
                max                             30
            }
            particle_height                     dyn_random
            {
                min                             30
                max                             60
            }
            position                            500 -400 0
            direction                           0.2 -1 0
            end_texture_coords_range            3
            colour                              0.752941 0.752941 0.752941 0.392157
            box_width                           2500
            box_height                          1
            box_depth                           2500
        }
        affector                                TextureRotator Affector16
        {
            rotation                            3.1
            rotation_speed                      0
        }
    }
    technique Technique6
    {
        visual_particle_quota                   1000
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/bomb_shockwave_atlas_01
        renderer                                Billboard
        {
            texture_coords_rows                 8
            texture_coords_columns              8
        }
        emitter                                 Box Emitter6
        {
            emission_rate                       1000
            time_to_live                        0.5
            velocity                            1e-05
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             50
            }
            position                            500 -1550 0
            colour                              1 1 1 0.392157
            box_width                           2500
            box_height                          1
            box_depth                           2500
        }
        affector                                TextureAnimator Affector12
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector17
        {
            time_colour                         0    0 0 0 0.6
            time_colour                         1    0 0 0 0
        }
    }
}
