system rift/boss_trail_energy
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.02
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 20
    technique sparks_trail
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       25
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             200
                max                             400
            }
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             5
            }
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           175
            box_height                          175
            box_depth                           175
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
        affector                                LinearForce Affector17
        {
            force_vector                        0 -1000 0
        }
        affector                                Scale Affector77
        {
            y_scale                             10
        }
    }
    technique lightning_small
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_bolt_4x4_blue_01
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       200
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             25
                max                             50
            }
            end_texture_coords_range            3
            box_width                           175
            box_height                          175
            box_depth                           175
        }
        affector                                Colour 
        {
            time_colour                         0    0.5 0.5 0.5 1
            time_colour                         0.143478  0.5 0.5 0.5 1
            time_colour                         1    0.5 0.5 0.5 0
            colour_operation                    multiply
        }
        affector                                TextureRotator Affector18
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
    }
}
