system rift/bradron_laser_hit
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.02
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 15
    technique 
    {
        position                                0 10 0
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       8
            angle                               5
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            particle_width                      dyn_random
            {
                min                             120
                max                             180
            }
            particle_height                     dyn_random
            {
                min                             180
                max                             240
            }
            direction                           0.4 1 0
            start_colour_range                  0.392157 0.745098 0 1
            end_colour_range                    0.235294 0.501961 0 1
            box_width                           20
            box_height                          20
            box_depth                           20
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 0 0
            time_colour                         0.11087  1 0 0 0.4
            time_colour                         1    1 0 0 0
        }
        affector                                TextureAnimator Affector12
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                TextureRotator Affector7
        {
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -1
                max                             1
            }
        }
        affector                                LinearForce Affector90
        {
            force_vector                        15 35 0
            force_application                   average
        }
    }
    technique sparks
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_red_01
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface add_flame_blue
        {
            emission_rate                       250
            angle                               45
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             500
                max                             1000
            }
            all_particle_dimensions             dyn_random
            {
                min                             4
                max                             8
            }
            direction                           -1 0 0
            radius                              20
        }
        affector                                Colour Affector197
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                LinearForce Affector191
        {
            force_vector                        0 -500 0
        }
        affector                                Scale Affector192
        {
            y_scale                             dyn_curved_linear
            {
                control_point                   0 100
                control_point                   1 -100
            }
        }
    }
    technique sparks2
    {
        keep_local                              true
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_red_01
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface add_flame_blue
        {
            emission_rate                       250
            angle                               90
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            all_particle_dimensions             dyn_random
            {
                min                             4
                max                             8
            }
            radius                              20
        }
        affector                                Colour Affector197
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.504348  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                LinearForce Affector191
        {
            force_vector                        0 -100 0
        }
        affector                                Scale Affector192
        {
            y_scale                             dyn_curved_linear
            {
                control_point                   0 100
                control_point                   1 -100
            }
        }
    }
    technique lightning_directional_0
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_atlas_01
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    top_center
            billboard_rotation_type             vertex
        }
        emitter                                 Box add_flame_blue
        {
            emission_rate                       30
            angle                               0
            time_to_live                        0.3
            velocity                            0.1
            particle_width                      100
            particle_height                     200
            keep_local                          true
            direction                           -1 0 0
            end_texture_coords_range            3
            colour                              0 1 1 1
            box_width                           40
            box_height                          40
            box_depth                           40
        }
        affector                                TextureRotator Affector168
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -4
                max                             -2.2
            }
            rotation_speed                      0
        }
        affector                                Colour Affector197
        {
            time_colour                         0    1 0 0 0
            time_colour                         0.104348  1 0 0 1
            time_colour                         1    1 0 0 0
        }
        affector                                Scale Affector9
        {
            x_scale                             dyn_random
            {
                min                             1000
                max                             2000
            }
            y_scale                             dyn_random
            {
                min                             500
                max                             1500
            }
        }
    }
    technique lightning_directional_1
    {
        visual_particle_quota                   40
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_atlas_01
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    top_center
            billboard_rotation_type             vertex
        }
        emitter                                 Box add_flame_blue
        {
            emission_rate                       8
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            velocity                            0.1
            all_particle_dimensions             dyn_random
            {
                min                             75
                max                             150
            }
            keep_local                          true
            direction                           -1 0 0
            end_texture_coords_range            3
            colour                              0 1 1 1
            box_width                           40
            box_height                          40
            box_depth                           40
        }
        affector                                TextureRotator Affector168
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -2.2
                max                             -4
            }
            rotation_speed                      0
        }
        affector                                Colour Affector197
        {
            time_colour                         0    1 0 0 0
            time_colour                         0.104348  1 0 0 1
            time_colour                         1    1 0 0 0
        }
        affector                                Scale Affector9
        {
            x_scale                             dyn_random
            {
                min                             1000
                max                             2000
            }
            y_scale                             dyn_random
            {
                min                             500
                max                             1500
            }
        }
    }
    technique 
    {
        keep_local                              true
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_atlas_01
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_rotation_type             vertex
        }
        emitter                                 Box StreakEmitter
        {
            emission_rate                       2
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            all_particle_dimensions             100
            keep_local                          true
            direction                           0 0 0
            end_texture_coords_range            3
            box_width                           50
            box_height                          50
            box_depth                           50
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 0 1
            time_colour                         1    1 0 0 0
        }
        affector                                Scale 
        {
            xyz_scale                           dyn_curved_linear
            {
                control_point                   0 200
                control_point                   0.8 200
                control_point                   1 400
            }
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
    }
    technique flash2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_red_01
        renderer                                Billboard
        {
            render_queue_group                  65
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 SphereSurface flash2
        {
            emission_rate                       25
            time_to_live                        0.35
            velocity                            0
            all_particle_dimensions             50
            keep_local                          true
            colour                              0.776471 0.388235 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                Scale Affector78
        {
            xyz_scale                           dyn_random
            {
                min                             150
                max                             200
            }
        }
        affector                                TextureRotator Affector128
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.2
                max                             0.4
            }
        }
    }
    technique flare2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            emission_rate                       25
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             150
            }
            keep_local                          true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.2  1 0 0 1
            time_colour                         0.802174  1 0 0 0.686275
            time_colour                         1    0 0 0 0
        }
        affector                                Scale Affector77
        {
            xyz_scale                           dyn_random
            {
                min                             100
                max                             200
            }
        }
    }
}
