system rift/carbonium_factory_hammer
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.015
    scale                                       0.015 0.015 0.015
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 20
    technique smoke_dirt
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_explosion_dirt
        renderer                                Billboard
        {
            render_queue_group                  62
        }
        emitter                                 Box Emitter1
        {
            emission_rate                       20
            angle                               45
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             200
                max                             300
            }
            duration                            1.5
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             100
            }
            colour                              1 0.501961 0 1
            box_width                           50
            box_height                          50
            box_depth                           50
        }
        affector                                Colour Affector35
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.708696  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                LinearForce Affector22
        {
            force_vector                        0 -500 0
        }
    }
    technique rocks
    {
        visual_particle_quota                   25
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       30
            angle                               60
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             400
                max                             500
            }
            duration                            1.5
            all_particle_dimensions             dyn_random
            {
                min                             15
                max                             25
            }
            end_texture_coords_range            15
            start_colour_range                  0.501961 0.501961 0.501961 1
            end_colour_range                    0.313726 0.313726 0.313726 1
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -800 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector18
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         0.806522  0.501961 0.501961 0.501961 1
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
    }
}
