system rift/cosmic_ring
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.045
    scale                                       0.045 0.045 0.045
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 1
    technique rings_alpha_3
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/planet_ring_01_add
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       100
            angle                               0
            time_to_live                        10000
            velocity                            0.001
            all_particle_dimensions             1100
            position                            0 1 0
            colour                              0.1 0.16 0.26 1
            force_emission                      true
        }
        affector                                TextureRotator Affector31
        {
            rotation_speed                      0.2
        }
    }
    technique rings_alpha_3
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/planet_ring_01_add
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       100
            angle                               0
            time_to_live                        10000
            velocity                            0.001
            all_particle_dimensions             1000
            position                            0 1 0
            colour                              0.1 0.16 0.26 1
            force_emission                      true
        }
        affector                                TextureRotator Affector31
        {
            rotation_speed                      0.15
        }
    }
    technique rings_alpha_3
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/planet_ring_01_add
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       100
            angle                               0
            time_to_live                        10000
            velocity                            0.001
            all_particle_dimensions             900
            position                            0 1 0
            colour                              0.1 0.16 0.26 1
            force_emission                      true
        }
        affector                                TextureRotator Affector31
        {
            rotation_speed                      0.1
        }
    }
    technique fog
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_e_add
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             40
                max                             64
            }
            direction                           -1 0 0
            colour                              0.1 0.16 0.26 1
            radius                              340
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique fog
    {
        visual_particle_quota                   150
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_e_add
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             40
                max                             64
            }
            direction                           -1 0 0
            colour                              0.1 0.16 0.26 1
            radius                              360
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique fog
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_e_add
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             40
                max                             64
            }
            direction                           -1 0 0
            colour                              0.1 0.16 0.26 1
            radius                              380
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique dust2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             4
            }
            direction                           -1 0 0
            end_texture_coords_range            15
            radius                              330
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique dust2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             4
            }
            direction                           -1 0 0
            end_texture_coords_range            15
            radius                              340
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique dust2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             4
            }
            direction                           -1 0 0
            end_texture_coords_range            15
            radius                              350
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique dust2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             4
            }
            direction                           -1 0 0
            end_texture_coords_range            15
            radius                              360
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique dust2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             4
            }
            direction                           -1 0 0
            end_texture_coords_range            15
            radius                              370
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique dust2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             4
            }
            direction                           -1 0 0
            end_texture_coords_range            15
            radius                              380
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique dust2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             4
            }
            direction                           -1 0 0
            end_texture_coords_range            15
            radius                              390
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
    technique dust2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle dust
        {
            emission_rate                       250
            angle                               0
            time_to_live                        10000
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             4
            }
            direction                           -1 0 0
            end_texture_coords_range            15
            radius                              400
        }
        affector                                Vortex Affector15
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             -0.01
                max                             -0.02
            }
        }
        affector                                TextureRotator Affector33
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.2
                max                             0.2
            }
        }
    }
}
