system rift/crash_site_core_weather
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.025
    scale                                       0.025 0.025 0.025
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 1
    technique 
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       200
            time_to_live                        dyn_random
            {
                min                             3
                max                             5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             175
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             4
            }
            position                            0 -400 0
            direction                           0.2 -1 0
            colour                              0.188235 0.188235 0.188235 1
            box_width                           2000
            box_height                          300
            box_depth                           2000
        }
        affector                                Colour Affector11
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.128261  0.74902 0.74902 0.74902 1
            time_colour                         0.230435  0 0 0 1
            time_colour                         0.332609  0.501961 0.501961 0.501961 1
            time_colour                         0.486957  0 0 0 1
            time_colour                         0.632609  0.74902 0.74902 0.74902 1
            time_colour                         0.752174  0 0 0 1
            time_colour                         0.836957  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
        affector                                SineForce Affector17
        {
            force_vector                        250 50 250
            max_frequency                       5
        }
        affector                                ForceField Affector26
        {
            movement                            250 0 0
        }
    }
    technique 
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       200
            time_to_live                        dyn_random
            {
                min                             3
                max                             5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             175
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             4
            }
            position                            0 -400 0
            direction                           0.2 -1 0
            colour                              0.188235 0.188235 0.188235 1
            box_width                           2000
            box_height                          300
            box_depth                           2000
        }
        affector                                Colour Affector11
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.128261  0.74902 0.74902 0.74902 1
            time_colour                         0.230435  0 0 0 1
            time_colour                         0.332609  0.501961 0.501961 0.501961 1
            time_colour                         0.486957  0 0 0 1
            time_colour                         0.632609  0.74902 0.74902 0.74902 1
            time_colour                         0.752174  0 0 0 1
            time_colour                         0.836957  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
        affector                                SineForce Affector17
        {
            force_vector                        -250 50 250
            max_frequency                       5
        }
        affector                                ForceField Affector26
        {
            movement                            250 0 0
        }
    }
    technique 
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       100
            time_to_live                        dyn_random
            {
                min                             3
                max                             5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             175
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             4
            }
            position                            0 -200 0
            direction                           0.2 -1 0
            colour                              0.313726 0.313726 0.313726 1
            box_width                           2000
            box_height                          10
            box_depth                           2000
        }
        affector                                Colour Affector10
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.128261  0.74902 0.74902 0.74902 1
            time_colour                         0.230435  0 0 0 1
            time_colour                         0.332609  0.501961 0.501961 0.501961 1
            time_colour                         0.486957  0 0 0 1
            time_colour                         0.632609  0.74902 0.74902 0.74902 1
            time_colour                         0.752174  0 0 0 1
            time_colour                         0.836957  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
}
