system rift/damage_radius_explosion_orange
{
    fixed_timeout                               0.5
    nonvisible_update_timeout                   1
    scale_velocity                              0.04
    scale                                       0.04 0.04 0.04
    tight_bounding_box                          true
    category                                    RIFT
    cache_count                                 30
    technique firealpha2
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion8
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       50
            angle                               80
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             30
                max                             60
            }
            all_particle_dimensions             dyn_random
            {
                min                             600
                max                             600
            }
            position                            0 100 0
            force_emission                      true
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.3
                max                             0.3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.22
                max                             0.22
            }
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector68
        {
            time_colour                         0    0.35 0.35 0.35 1
            time_colour                         0.5  0.35 0.35 0.35 1
            time_colour                         1    0.35 0.35 0.35 0
        }
    }
    technique sparks
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        0.5
            velocity                            dyn_random
            {
                min                             750
                max                             1000
            }
            particle_width                      5
            particle_height                     dyn_random
            {
                min                             5
                max                             25
            }
            position                            0 25 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 1
            time_colour                         0.5  0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
    }
    technique lines
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_trail2
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 17
            texture_coords_columns              5
            billboard_type                      oriented_self
            billboard_origin                    center_left
            billboard_rotation_type             vertex
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               100
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      dyn_random
            {
                min                             300
                max                             400
            }
            particle_height                     dyn_random
            {
                min                             60
                max                             120
            }
            end_texture_coords_range            84
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.5 0.5 0.5 1
            time_colour                         0.5  0.5 0.5 0.5 1
            time_colour                         1    0.5 0.5 0.5 0
        }
        affector                                TextureAnimator Affector45
        {
            end_texture_coords_range            84
            texture_start_random                false
        }
        affector                                TextureRotator Affector46
        {
            rotation                            -1.6
            rotation_speed                      0
        }
    }
    technique refract_shockwave
    {
        enabled                                 false
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             100
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1200
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
}
