system exor/destructible_cloth
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.0250
    scale                                       0.0250 0.0250 0.0250
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique smoke
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box smoke
        {
            emission_rate                       25
            angle                               85
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             40
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             75
                max                             100
            }
            end_texture_coords_range            3
            start_colour_range                  0.501961 0.501961 0.25098 1
            end_colour_range                    0.501961 0.501961 0.50196 1
            force_emission                      true
            box_height                          200
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 0.6
            time_colour                         0.506522  0.752941 0.752941 0.752941 0.4
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                LinearForce Affector10
        {
            force_vector                        0 -40 0
        }
        affector                                Scale Affector19
        {
            xyz_scale                           60
            since_start_system                  true
        }
    }
    technique leaves
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/cloth_parts
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       50
            angle                               90
            velocity                            dyn_random
            {
                min                             20
                max                             25
            }
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             60
            }
            start_colour_range                  0 0.501961 0 1
            end_colour_range                    0 0.2 0 1
            colour                              0 0.501961 0 1
            force_emission                      true
            box_width                           75
            box_depth                           75
        }
        affector                                LinearForce 
        {
            force_vector                        0 -50 0
        }
        affector                                TextureRotator Affector25
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -1
                max                             1
            }
        }
        affector                                Colour Affector46
        {
            time_colour                         0    0.752941 0.752941 0.752941 1
            time_colour                         0.502174  0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
    }
    technique wood
    {
        visual_particle_quota                   15
        emitted_emitter_quota                   1
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/cloth_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       50
            angle                               90
            velocity                            dyn_random
            {
                min                             350
                max                             500
            }
            particle_width                      dyn_random
            {
                min                             10
                max                             25
            }
            particle_height                     dyn_random
            {
                min                             10
                max                             40
            }
            end_texture_coords_range            3
            start_colour_range                  0 1 0 1
            end_colour_range                    0 0.25098 0 1
            colour                              0 0.501961 0 1
            auto_direction                      true
            force_emission                      true
            box_width                           15
            box_depth                           15
        }
        affector                                LinearForce 
        {
            force_vector                        0 -700 0
        }
        affector                                TextureRotator Affector25
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -1
                max                             1
            }
        }
        affector                                Colour Affector47
        {
            time_colour                         0    0.74902 0.74902 0.74902 1
            time_colour                         0.508696  0.74902 0.74902 0.74902 1
            time_colour                         1    0.74902 0.74902 0.74902 0
        }
    }
}
