system exor/destructible_flowers
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.0250
    scale                                       0.0250 0.0250 0.0250
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique leaves
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/wood_splinter03
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       50
            angle                               90
            velocity                            dyn_random
            {
                min                             20
                max                             25
            }
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             60
            }
            position                            0 15 0
            start_colour_range                  0 0.501961 0 1
            end_colour_range                    0 0.2 0 1
            colour                              0 0.501961 0 1
            force_emission                      true
            box_height                          20
        }
        affector                                LinearForce 
        {
            force_vector                        0 -50 0
        }
        affector                                TextureRotator Affector25
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -1
                max                             1
            }
        }
        affector                                Colour Affector46
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.504348  1 1 1 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
    }
}
