system rift/destructible_crystal_small_orange
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.012
    scale                                       0.012 0.012 0.012
    tight_bounding_box                          true
    category                                    RIFT
    cache_count                                 30
    technique firealpha2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/impact_dust_anim_03_8x4
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       50
            angle                               80
            time_to_live                        dyn_random
            {
                min                             1.5
                max                             2
            }
            velocity                            dyn_random
            {
                min                             30
                max                             60
            }
            all_particle_dimensions             dyn_random
            {
                min                             220
                max                             276
            }
            position                            0 100 0
            force_emission                      true
            radius                              60
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.3
                max                             0.3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.22
                max                             0.22
            }
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                Colour Affector68
        {
            time_colour                         0    1 0.501961 0 0.494118
            time_colour                         1    1 0.501961 0 0.494118
        }
    }
    technique debris
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/crystal_shard_orange
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       100
            angle                               60
            time_to_live                        dyn_random
            {
                min                             2.5
                max                             3
            }
            velocity                            dyn_random
            {
                min                             1000
                max                             2000
            }
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             50
            }
            position                            0 25 0
            end_texture_coords_range            3
            colour                              0.1 0.1 0.1 1
            force_emission                      true
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -5000 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
        affector                                Colour Affector358
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.904348  1 1 1 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
    }
    technique refract_shockwave
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             100
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.5  1 1 1 0.709804
            time_colour                         1    0 0 0 0
        }
    }
}
