system rift/destructible_wall_swamp
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.04 0.04 0.04
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 20
    technique smoke
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box smoke
        {
            emission_rate                       25
            angle                               85
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             40
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             100
            }
            position                            0 90 0
            end_texture_coords_range            3
            start_colour_range                  0.501961 0.501961 0.25098 1
            end_colour_range                    0.501961 0.501961 0.50196 1
            auto_direction                      true
            force_emission                      true
            box_height                          300
        }
        affector                                Colour 
        {
            time_colour                         0    0.165158 0.247458 0.161057 0
            time_colour                         0.0978261  0.165158 0.247458 0.161057 0.257627
            time_colour                         1    0.165158 0.247458 0.161057 0
        }
        affector                                LinearForce Affector10
        {
            force_vector                        0 -40 0
        }
        affector                                Scale Affector19
        {
            xyz_scale                           dyn_random
            {
                min                             40
                max                             80
            }
            since_start_system                  true
        }
        affector                                TextureRotator Affector202
        {
            use_own_rotation                    true
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             1
            }
        }
    }
    technique parts_trail
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/leafs_1x4
        renderer                                Billboard
        {
            texture_coords_rows                 4
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       50
            angle                               90
            velocity                            dyn_random
            {
                min                             350
                max                             550
            }
            particle_width                      dyn_random
            {
                min                             6
                max                             15
            }
            particle_height                     dyn_random
            {
                min                             6
                max                             30
            }
            position                            0 25 0
            end_texture_coords_range            3
            colour                              0.501961 0.501961 0.501961 1
            force_emission                      true
            box_height                          200
        }
        affector                                LinearForce 
        {
            force_vector                        0 -700 0
        }
        affector                                TextureRotator Affector25
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -5
                max                             5
            }
        }
        affector                                Colour Affector79
        {
            time_colour                         0    0.0886482 0.688136 0 0
            time_colour                         0.202174  0.146764 0.698305 0 1
            time_colour                         0.708696  0.163306 0.708475 0 1
            time_colour                         1    0.117776 0.694915 0 0
        }
    }
    technique falling_debris
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/leafs_1x4
        renderer                                Billboard
        {
            texture_coords_rows                 4
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       100
            angle                               90
            time_to_live                        2
            velocity                            dyn_random
            {
                min                             3
                max                             4
            }
            duration                            1
            all_particle_dimensions             dyn_random
            {
                min                             8
                max                             16
            }
            position                            0 25 0
            end_texture_coords_range            3
            colour                              0.501961 0.501961 0.501961 1
            box_height                          300
        }
        affector                                LinearForce 
        {
            force_vector                        0 -600 0
        }
        affector                                TextureRotator Affector25
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -5
                max                             5
            }
        }
        affector                                Colour Affector79
        {
            time_colour                         0    0.0313751 0.661017 0 0
            time_colour                         0.202174  0.0882019 0.684746 0 1
            time_colour                         0.708696  0.0612498 0.694915 0 1
            time_colour                         1    0.0184736 0.681356 0 0
        }
    }
    technique falling_smoke
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       35
            angle                               90
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             3
                max                             4
            }
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             30
            }
            position                            0 20 0
            end_texture_coords_range            3
            colour                              0.501961 0.501961 0.501961 1
            force_emission                      true
            box_height                          300
        }
        affector                                LinearForce 
        {
            force_vector                        0 -350 0
        }
        affector                                Colour Affector79
        {
            time_colour                         0    0.165158 0.247458 0.161057 0
            time_colour                         0.41087  0.165158 0.247458 0.161057 0.305085
            time_colour                         0.708696  0.165158 0.247458 0.161057 0.294915
            time_colour                         1    0.165158 0.247458 0.161057 0
        }
        affector                                Scale Affector325
        {
            y_scale                             200
        }
    }
    technique parts_trail_1
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/leafs_1x4
        renderer                                Billboard
        {
            texture_coords_rows                 4
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       50
            angle                               90
            velocity                            dyn_random
            {
                min                             350
                max                             550
            }
            particle_width                      dyn_random
            {
                min                             6
                max                             15
            }
            particle_height                     dyn_random
            {
                min                             6
                max                             30
            }
            position                            0 25 0
            end_texture_coords_range            3
            colour                              0.501961 0.501961 0.501961 1
            force_emission                      true
            box_height                          200
        }
        affector                                LinearForce 
        {
            force_vector                        0 -700 0
        }
        affector                                TextureRotator Affector25
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -5
                max                             5
            }
        }
        affector                                Colour Affector79
        {
            time_colour                         0    1 0.549152 0 0
            time_colour                         0.202174  1 0.589831 0 1
            time_colour                         0.708696  1 0.589831 0 1
            time_colour                         1    1 0.569492 0 0
        }
    }
}
