system rift/earthquake
{
    nonvisible_update_timeout                   1
    disable_culling                             true
    scale_velocity                              0.04
    scale                                       0.04 0.04 0.04
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 17
    technique water
    {
        position                                0 30 0
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/water_foam_01
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 8
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Circle water
        {
            angle                               10
            time_to_live                        dyn_random
            {
                min                             1.5
                max                             2.5
            }
            velocity                            dyn_random
            {
                min                             20
                max                             25
            }
            all_particle_dimensions             dyn_random
            {
                min                             75
                max                             100
            }
            colour                              0.992157 0.992157 0.984314 1
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -2
                max                             2
            }
            rotation_speed                      dyn_random
            {
                min                             -0.1
                max                             0.1
            }
        }
        affector                                Colour 
        {
            time_colour                         0    0.568627 0.384314 0.247059 0
            time_colour                         0.0978261  0.568627 0.384314 0.247059 0.494118
            time_colour                         0.61087  0.568627 0.384314 0.247059 0.494118
            time_colour                         1    0.568627 0.384314 0.247059 0
        }
        affector                                ScaleVelocity 
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0 -356.665
                control_point                   2 -0.983379
            }
            since_start_system                  true
        }
        affector                                Scale 
        {
            x_scale                             dyn_random
            {
                min                             50
                max                             100
            }
            y_scale                             dyn_random
            {
                min                             100
                max                             200
            }
        }
        affector                                LinearForce 
        {
            force_vector                        0 5 0
        }
        affector                                TextureAnimator Affector30
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
    technique smoke_box
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_03_alpha_atlas
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_rotation_type             vertex
        }
        emitter                                 Box smoke_ring
        {
            emission_rate                       20
            angle                               15
            time_to_live                        dyn_random
            {
                min                             4
                max                             5
            }
            velocity                            dyn_random
            {
                min                             10
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             80
            }
            position                            0 25 0
            end_texture_coords_range            3
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            auto_direction                      true
            box_width                           500
            box_height                          10
            box_depth                           500
        }
        affector                                Colour 
        {
            time_colour                         0    0.568627 0.384314 0.247059 0
            time_colour                         0.3  0.568627 0.384314 0.247059 0.5
            time_colour                         1    0.568627 0.384314 0.247059 0
        }
        affector                                Scale 
        {
            xyz_scale                           30
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.4
                max                             0.4
            }
            rotation_speed                      0
        }
        affector                                ScaleVelocity Affector33
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0 -0.31025
                control_point                   1 -140.9
            }
            stop_at_flip                        true
        }
    }
    technique smoke_ring
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_03_alpha_atlas
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_rotation_type             vertex
        }
        emitter                                 Circle smoke_ring
        {
            emission_rate                       20
            angle                               15
            time_to_live                        dyn_random
            {
                min                             4
                max                             5
            }
            velocity                            dyn_random
            {
                min                             10
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             80
            }
            position                            0 25 0
            end_texture_coords_range            3
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            auto_direction                      true
            radius                              350
        }
        affector                                Colour 
        {
            time_colour                         0    0.568627 0.384314 0.247059 0
            time_colour                         0.3  0.568627 0.384314 0.247059 0.247059
            time_colour                         1    0.568627 0.384314 0.247059 0
        }
        affector                                Scale 
        {
            xyz_scale                           30
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.4
                max                             0.4
            }
            rotation_speed                      0
        }
        affector                                ScaleVelocity Affector33
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0 -0.31025
                control_point                   1 -140.9
            }
            stop_at_flip                        true
        }
    }
    technique rocks
    {
        visual_particle_quota                   40
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       100
            angle                               60
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             90
                max                             120
            }
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             8
            }
            position                            0 50 0
            end_texture_coords_range            15
            start_colour_range                  0.501961 0.501961 0.501961 1
            end_colour_range                    0.313726 0.313726 0.313726 1
            box_width                           600
            box_height                          10
            box_depth                           600
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -300 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector18
        {
            time_colour                         0    0.31 0.233 0.137 1
            time_colour                         0.806522  0.31 0.233 0.137 1
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
    }
    technique smoke_dirt
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_explosion_dirt
        renderer                                Billboard
        {
            render_queue_group                  62
        }
        emitter                                 Box Emitter1
        {
            emission_rate                       25
            angle                               45
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             70
            }
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             80
            }
            position                            0 50 0
            colour                              1 0.501961 0 1
            box_width                           600
            box_height                          10
            box_depth                           600
        }
        affector                                Colour Affector35
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.708696  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                LinearForce Affector22
        {
            force_vector                        0 -200 0
        }
        affector                                TextureRotator 
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             1
            }
        }
    }
}
