system rift/emergency_explosion
{
    fixed_timeout                               2.5
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.035 0.035 0.035
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 1
    technique sparks
    {
        visual_particle_quota                   60
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             300
                max                             500
            }
            particle_width                      dyn_random
            {
                min                             3
                max                             4
            }
            particle_height                     dyn_random
            {
                min                             8
                max                             25
            }
            position                            0 50 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
        affector                                Scale Affector20
        {
            y_scale                             -3
        }
    }
    technique refract_shockwave
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        1
            velocity                            0
            all_particle_dimensions             100
            position                            0 5 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.752181  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique smoke_ring
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle smoke_ring
        {
            emission_rate                       2000
            angle                               15
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             0.95
            }
            velocity                            dyn_random
            {
                min                             400
                max                             410
            }
            all_particle_dimensions             dyn_random
            {
                min                             125
                max                             150
            }
            position                            0 50 0
            auto_direction                      true
            force_emission                      true
            radius                              50
        }
        affector                                Colour 
        {
            time_colour                         0    0.239216 0.239216 0.176471 0
            time_colour                         0.1  0.239216 0.239216 0.176471 0.6
            time_colour                         0.708696  0.231373 0.231373 0.164706 0.607843
            time_colour                         1    0.239216 0.239216 0.176471 0
        }
        affector                                TextureAnimator Affector25
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
    technique sparks_1
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris_blood
        {
            emission_rate                       100
            angle                               90
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             1
            }
            velocity                            dyn_random
            {
                min                             50
                max                             400
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             4
            }
            position                            0 5 0
            force_emission                      true
            box_width                           25
            box_height                          25
            box_depth                           25
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.470667  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -200 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
    }
    technique firealpha2
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_anim_01
        renderer                                Billboard
        {
            texture_coords_rows                 8
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       500
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.7
            }
            velocity                            dyn_random
            {
                min                             0
                max                             400
            }
            all_particle_dimensions             dyn_random
            {
                min                             25
                max                             60
            }
            position                            0 15 0
            keep_local                          true
            end_texture_coords_range            31
            auto_direction                      true
            force_emission                      true
            radius                              10
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.3
                max                             0.3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.22
                max                             0.22
            }
        }
        affector                                Colour Affector68
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureAnimator Affector22
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                Scale 
        {
            xyz_scale                           -20
        }
    }
    technique sparks_2
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Circle DebrisEmitter
        {
            emission_rate                       100
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             300
                max                             500
            }
            particle_width                      dyn_random
            {
                min                             3
                max                             4
            }
            particle_height                     dyn_random
            {
                min                             8
                max                             25
            }
            position                            0 5 0
            start_colour_range                  1 1 1 1
            auto_direction                      true
            force_emission                      true
            radius                              1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
        affector                                Scale Affector20
        {
            y_scale                             -3
        }
    }
    technique debris_blood
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris_blood
        {
            emission_rate                       100
            angle                               80
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             200
                max                             750
            }
            all_particle_dimensions             dyn_random
            {
                min                             6
                max                             15
            }
            end_texture_coords_range            15
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.542373 0.452197 0.250043 1
            time_colour                         0.704348  0.542373 0.44865 0.273944 1
            time_colour                         1    0.535593 0.456791 0.295938 0
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -800 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
    }
}
