system exor/enemy_cannon_bullet_very_big
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.0050
    scale                                       0.0050 0.0050 0.0050
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 0
    technique 
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/enemy_bullet_very_big_01
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
            common_direction                    1 0 0
            common_up_vector                    1 0 0
            accurate_facing                     true
        }
        emitter                                 Point 
        {
            emission_rate                       50
            angle                               0
            time_to_live                        20
            velocity                            0.001
            particle_width                      600
            particle_height                     1200
            direction                           1 0 0
            force_emission                      true
        }
        affector                                Colour Affector2
        {
            time_colour                         0    1 0 0 1
            time_colour                         0.1  0.301961 0 0 1
            time_colour                         0.2  1 0 0 1
            time_colour                         0.3  0.301961 0 0 1
            time_colour                         0.4  1 0 0 1
            time_colour                         0.5  0.301961 0 0 1
            time_colour                         0.6  1 0 0 1
            time_colour                         0.7  0.301961 0 0 1
            time_colour                         0.8  1 0 0 1
            time_colour                         0.9  0.301961 0 0 1
            time_colour                         1    1 0 0 0
            colour_operation                    multiply
        }
    }
    technique glow
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_nocolor
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
            common_direction                    1 0 0
            common_up_vector                    1 0 0
            accurate_facing                     true
        }
        emitter                                 Point 
        {
            emission_rate                       50
            angle                               0
            time_to_live                        20
            velocity                            0.001
            particle_width                      900
            particle_height                     900
            position                            350 0 0
            direction                           1 0 0
            colour                              1 0.05 0 0.5
            force_emission                      true
        }
        affector                                Colour Affector3
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.754348  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
    technique sparks2
    {
        keep_local                              true
        visual_particle_quota                   60
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_orange_01
        renderer                                Billboard
        {
            render_queue_group                  69
            billboard_type                      oriented_self
            billboard_origin                    top_center
            billboard_rotation_type             vertex
        }
        emitter                                 Box trail111
        {
            emission_rate                       40
            angle                               3
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             0.7
            }
            velocity                            dyn_random
            {
                min                             1000
                max                             2000
            }
            duration                            20
            particle_width                      dyn_random
            {
                min                             30
                max                             40
            }
            particle_height                     dyn_random
            {
                min                             50
                max                             100
            }
            position                            350 0 0
            direction                           -1 0 0
            box_width                           50
            box_height                          50
            box_depth                           50
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0.239216
            time_colour                         0.508696  1 1 1 0.239216
            time_colour                         1    1 1 1 0
        }
        affector                                Scale Affector35
        {
            xyz_scale                           -3
        }
    }
    technique front
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/enemy_bullet_very_big_front_01
        renderer                                Billboard
        {
            render_queue_group                  69
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    1 0 0
            accurate_facing                     true
        }
        emitter                                 Point 
        {
            emission_rate                       50
            angle                               0
            time_to_live                        20
            velocity                            0.001
            all_particle_dimensions             140
            position                            470 0 0
            direction                           1 0 0
            colour                              1 1 1 0.498039
            force_emission                      true
        }
    }
}
