system exor/enemy_missile_small
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.0450
    scale                                       0.0450 0.0450 0.0450
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique trail1
    {
        keep_local                              true
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_add_03
        renderer                                Billboard
        {
            render_queue_group                  66
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point trail1
        {
            emission_rate                       100
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.2
            }
            velocity                            1
            particle_width                      5
            particle_height                     10
            position                            -5 0 0
            direction                           -1 0 0
        }
        affector                                Scale 
        {
            x_scale                             -10
            y_scale                             50
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.2  1 1 1 0
            time_colour                         0.8  0.658824 0.329412 0 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
    }
    technique trail3
    {
        keep_local                              true
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_weapon_rocketboost
        renderer                                Billboard
        {
            render_queue_group                  66
            texture_coords_rows                 0
            texture_coords_columns              0
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point trail3
        {
            emission_rate                       300
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.2
            }
            velocity                            1
            particle_width                      dyn_random
            {
                min                             0.5
                max                             2.5
            }
            particle_height                     dyn_random
            {
                min                             2.5
                max                             7.5
            }
            position                            -5 0 0
            direction                           -1 0 0
        }
        affector                                Scale 
        {
            x_scale                             -20
            y_scale                             25
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.8  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
    technique flare
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_woosh_glow_01
        default_particle_width                  250
        default_particle_height                 250
        default_particle_depth                  250
        renderer                                Billboard
        {
            render_queue_group                  66
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       100
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            velocity                            0.0001
            all_particle_dimensions             25
            position                            -5 0 0
            colour                              1 0.501961 0.25098 1
        }
    }
    technique ribbon
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/ribbon_enemy_missile
        renderer                                RibbonTrail
        {
            render_queue_group                  65
            max_elements                        20
            ribbontrail_length                  500
            ribbontrail_width                   25
            random_initial_colour               false
            colour_change                       0.501961 0.501961 0.501961 0.392157
        }
        emitter                                 Point 
        {
            emission_rate                       1000
            angle                               0
            time_to_live                        5
            velocity                            0.0001
            position                            5 0 0
            direction                           1 0 0
            force_emission                      true
        }
    }
}
