system exor/enemy_missile_artillery_boss_slow
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.0500
    scale                                       0.0500 0.0500 0.0500
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique smoke_trail
    {
        visual_particle_quota                   75
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       50
            angle                               2
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             75
            }
            all_particle_dimensions             dyn_random
            {
                min                             5
                max                             10
            }
            direction                           -1 0 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           5
            box_height                          5
            box_depth                           5
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0.752941 0.752941 0.752941 0.109804
            time_colour                         0.206522  0.501961 0.501961 0.501961 0.247059
            time_colour                         0.608696  0.27451 0.27451 0.27451 0.247059
            time_colour                         1    0.266667 0.266667 0.266667 0
        }
        affector                                TextureRotator Affector6
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             0.5
                max                             -0.5
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
        affector                                Scale Affector79
        {
            xyz_scale                           10
        }
    }
}
