system exor/enemy_bomb_explosion_big
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.0450
    scale                                       0.0450 0.0450 0.0450
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique firealpha
    {
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/explosion_and_smoke_anim_01
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       50
            angle                               80
            time_to_live                        dyn_random
            {
                min                             2
                max                             2.5
            }
            velocity                            dyn_random
            {
                min                             30
                max                             60
            }
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             74
            }
            position                            0 50 0
            force_emission                      true
            radius                              60
        }
        affector                                Scale 
        {
            xyz_scale                           100
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.4
                max                             0.4
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector68
        {
            time_colour                         0    0.2 0.2 0.2 1
            time_colour                         0.506522  0.2 0.2 0.2 1
            time_colour                         1    0.2 0.2 0.2 0
        }
    }
    technique sparks
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             1
                max                             1
            }
            velocity                            dyn_random
            {
                min                             500
                max                             750
            }
            particle_width                      3
            particle_height                     dyn_random
            {
                min                             3
                max                             25
            }
            position                            0 50 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.2 0.2 0.2 1
            time_colour                         0.502174  0.2 0.2 0.2 1
            time_colour                         1    0.2 0.2 0.2 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
    }
    technique debris
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/metal_scrap_anim
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 2
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       100
            angle                               60
            time_to_live                        dyn_random
            {
                min                             2
                max                             3
            }
            velocity                            dyn_random
            {
                min                             500
                max                             750
            }
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             50
            }
            position                            0 50 0
            colour                              0.313726 0.313726 0.313726 1
            force_emission                      true
        }
        affector                                TextureAnimator Affector49
        {
            time_step                           0.04
            end_texture_coords_range            15
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -800 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
    }
    technique lines
    {
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_ember_nocolor_add_01
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            particle_width                      50
            particle_height                     dyn_random
            {
                min                             150
                max                             200
            }
            position                            0 50 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 0.501961 0 1
            time_colour                         1    0 0 0 1
        }
    }
    technique ring
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_01
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.7
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    0.603922 0.603922 0 1
            time_colour                         0.502174  0.592157 0.294118 0 1
            time_colour                         1    0 0 0 0
        }
    }
    technique smoke_ring
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle smoke_ring
        {
            emission_rate                       100
            angle                               15
            time_to_live                        dyn_random
            {
                min                             0.75
                max                             0.85
            }
            velocity                            dyn_random
            {
                min                             400
                max                             410
            }
            all_particle_dimensions             dyn_random
            {
                min                             125
                max                             150
            }
            position                            0 50 0
            auto_direction                      true
            force_emission                      true
            radius                              50
        }
        affector                                Colour 
        {
            time_colour                         0    0.239216 0.239216 0.176471 0
            time_colour                         0.1  0.239216 0.239216 0.176471 0.6
            time_colour                         0.708696  0.231373 0.231373 0.164706 0.447059
            time_colour                         1    0.239216 0.239216 0.176471 0
        }
        affector                                LinearForce Affector31
        {
            force_vector                        0 40 0
        }
        affector                                TextureAnimator Affector25
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
    technique refract_shockwave
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             100
            position                            0 50 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           3000
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
        }
    }
}
