system exor/enemy_emp_field_circle
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.0450
    scale                                       0.0450 0.0450 0.0450
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique lightning_space
    {
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_bolt_4x2_violet_01
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box DebrisEmitter
        {
            emission_rate                       5
            angle                               1
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            0.1
            all_particle_dimensions             dyn_random
            {
                min                             150
                max                             300
            }
            direction                           0 0 1
            end_texture_coords_range            3
            start_colour_range                  1 1 1 1
            box_depth                           300
        }
        affector                                Colour 
        {
            time_colour                         0    0.498039 0.498039 0.498039 0
            time_colour                         0.304348  0.498039 0.498039 0.498039 0
            time_colour                         0.606522  0.498039 0.498039 0.498039 0.509804
            time_colour                         0.758696  0.498039 0.498039 0.498039 0.509804
            time_colour                         1    0.498039 0.498039 0.498039 0
        }
    }
}
