system exor/enemy_air_mine_proximity_radius
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.0150
    scale                                       0.0250 0.0250 0.0250
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 0
    technique shockwave1
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/shockwave_02_add
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash1
        {
            time_to_live                        1
            velocity                            0
            all_particle_dimensions             40
        }
        affector                                Scale flash2
        {
            xyz_scale                           600
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0.2
            time_colour                         0.502174  1 0 0 0.109804
            time_colour                         1    0 0 0 0
        }
    }
    technique refract
    {
        keep_local                              true
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            emission_rate                       2
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             400
        }
        affector                                Scale flash2
        {
            xyz_scale                           600
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0.4
            time_colour                         0.506522  1 1 1 0.4
            time_colour                         1    1 1 1 0
        }
    }
}
