system rift/error
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.03
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    technique s2
    {
        visual_particle_quota                   8
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/error
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_rotation_type             vertex
        }
        emitter                                 Box s2
        {
            emission_rate                       2
            angle                               dyn_random
            {
                min                             5
                max                             10
            }
            time_to_live                        dyn_random
            {
                min                             3
                max                             4
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             200
            }
            direction                           0.5 1 0
            start_colour_range                  1 1 1 1
            colour                              0 0 0 1
            box_width                           120
            box_height                          120
            box_depth                           120
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.3  1 1 1 0.3
            time_colour                         0.86087  1 1 1 0.3
            time_colour                         1    1 1 1 0
        }
        affector                                Scale 
        {
            xyz_scale                           50
        }
        affector                                TextureRotator Affector104
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             0.2
            }
        }
    }
}
