system rift/excavator_hit
{
    fixed_timeout                               0.6
    nonvisible_update_timeout                   1
    scale_velocity                              0.01
    scale                                       0.01 0.01 0.01
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 15
    technique rocks
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       100
            angle                               90
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             0.6
            }
            velocity                            dyn_random
            {
                min                             800
                max                             1000
            }
            all_particle_dimensions             dyn_random
            {
                min                             15
                max                             30
            }
            end_texture_coords_range            15
            start_colour_range                  0.501961 0.501961 0.501961 1
            end_colour_range                    0.313726 0.313726 0.313726 1
            force_emission                      true
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -2500 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector18
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         0.806522  0.501961 0.501961 0.501961 1
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
    }
}
