system rift/explosion_building_energy_storage
{
    fixed_timeout                               2
    nonvisible_update_timeout                   1
    scale_velocity                              0.025
    scale                                       0.025 0.025 0.025
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 4
    technique fireblue2
    {
        visual_particle_quota                   8
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/explosion_blue_anim_04
        renderer                                Billboard
        {
            render_queue_group                  60
            texture_coords_rows                 8
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       50
            angle                               1
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             1
            }
            velocity                            dyn_random
            {
                min                             30
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             250
                max                             302
            }
            position                            0 50 0
            auto_direction                      true
            force_emission                      true
            radius                              30
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            15
            texture_start_random                false
        }
        affector                                LinearForce Affector21
        {
            force_vector                        0 25 0
        }
        affector                                TextureRotator Affector106
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -2
                max                             2
            }
            rotation_speed                      0
        }
        affector                                Colour Affector150
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.508696  1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
    }
    technique fireblue2
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/explosion_blue_anim_04
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 8
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       50
            angle                               1
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1.2
            }
            velocity                            dyn_random
            {
                min                             30
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             100
                max                             151
            }
            position                            0 50 0
            auto_direction                      true
            force_emission                      true
            radius                              30
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                LinearForce Affector21
        {
            force_vector                        0 25 0
        }
        affector                                TextureRotator Affector106
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -2
                max                             2
            }
            rotation_speed                      0
        }
        affector                                Colour Affector150
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
    }
    technique firealpha
    {
        visual_particle_quota                   25
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_explosion_water
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       50
            angle                               80
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             150
                max                             250
            }
            all_particle_dimensions             dyn_random
            {
                min                             100
                max                             150
            }
            position                            0 75 0
            force_emission                      true
            radius                              60
        }
        affector                                Scale 
        {
            xyz_scale                           100
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -1
                max                             1
            }
        }
        affector                                Colour Affector68
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.508696  0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique smoketrail1
    {
        visual_particle_quota                   150
        emitted_emitter_quota                   3
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        default_particle_width                  1
        default_particle_height                 1
        default_particle_depth                  1
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box baseEmitter
        {
            emission_rate                       3
            angle                               70
            time_to_live                        0.8
            velocity                            dyn_random
            {
                min                             700
                max                             1000
            }
            duration                            0.1
            all_particle_dimensions             0.001
            emits                               emitter_particle smoketrail1
            force_emission                      true
            box_width                           10
            box_height                          10
            box_depth                           10
        }
        emitter                                 SphereSurface smoketrail1
        {
            emission_rate                       dyn_curved_linear
            {
                control_point                   0 0.720219
                control_point                   0.158672 1.39613
                control_point                   0.352399 50.4931
                control_point                   1 0
            }
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             1
                max                             3
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             4
            }
        }
        affector                                LinearForce 
        {
            exclude_emitter                     smoketrail1 
            force_vector                        0 -600 0
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.508696  1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
        affector                                TextureRotator Affector6
        {
            rotation                            dyn_random
            {
                min                             -0.5
                max                             0.5
            }
            rotation_speed                      1
        }
        affector                                LinearForce Affector17
        {
            force_vector                        0 -100 0
        }
    }
    technique sparks
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             500
                max                             700
            }
            particle_width                      dyn_random
            {
                min                             5
                max                             8
            }
            particle_height                     dyn_random
            {
                min                             8
                max                             25
            }
            position                            0 50 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.506522  1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
        affector                                Scale Affector20
        {
            y_scale                             -3
        }
    }
    technique lines
    {
        visual_particle_quota                   25
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_muzzleflash_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            particle_width                      dyn_random
            {
                min                             30
                max                             60
            }
            particle_height                     dyn_random
            {
                min                             60
                max                             120
            }
            position                            0 50 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.506522  1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
        affector                                Scale Affector18
        {
            xyz_scale                           dyn_random
            {
                min                             400
                max                             600
            }
        }
    }
    technique debris
    {
        visual_particle_quota                   80
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/metal_scrap_blue_anim
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       100
            angle                               60
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             500
                max                             750
            }
            all_particle_dimensions             dyn_random
            {
                min                             5
                max                             25
            }
            position                            0 50 0
            force_emission                      true
        }
        affector                                TextureAnimator Affector49
        {
            time_step                           0.04
            end_texture_coords_range            15
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -800 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector358
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
    }
    technique shockwave_anim
    {
        visual_particle_quota                   6
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/explosion_fire_blue_02_anim
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              16
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        dyn_random
            {
                min                             0.9
                max                             1.1
            }
            velocity                            0
            all_particle_dimensions             500
            position                            0 5 0
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.493478  1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
        affector                                TextureAnimator Affector78
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                TextureRotator Affector21
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
    }
    technique shockwave_single
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/shockwave_02
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             1
            position                            0 5 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.506522  1 1 1 1
            time_colour                         1    1 1 1 0
        }
    }
    technique refract_shockwave
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             100
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1750
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.330435  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique flash2
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_nodepth_02
        renderer                                Billboard
        {
            render_queue_group                  65
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.25
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           5000
        }
        affector                                Colour 
        {
            time_colour                         0    0 0.501961 1 1
            time_colour                         0.502174  0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
    }
}
