system exor/fire_trail_03_short_cheap
{
    fixed_timeout                               1.3
    nonvisible_update_timeout                   1
    scale_velocity                              0.0400
    scale                                       0.0400 0.0400 0.0400
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique fire_alpha
    {
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_anim_01
        renderer                                Billboard
        {
            texture_coords_rows                 8
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       35
            time_to_live                        0.8
            velocity                            dyn_random
            {
                min                             25
                max                             35
            }
            duration                            dyn_random
            {
                min                             0.3
                max                             0.5
            }
            all_particle_dimensions             dyn_random
            {
                min                             14
                max                             20
            }
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           5
            box_height                          5
            box_depth                           5
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.104348  0.0784314 0.0784314 0.0784314 0.894118
            time_colour                         0.708696  0 0 0 0.694118
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector6
        {
            rotation                            dyn_random
            {
                min                             -0.5
                max                             0.5
            }
            rotation_speed                      1
        }
    }
}
