system rift/fire_ambient_blue_big
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.03
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 20
    technique fire_alpha
    {
        visual_particle_quota                   60
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/explosion_blue_anim_04
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 8
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Box fire_alpha
        {
            emission_rate                       20
            angle                               15
            time_to_live                        dyn_random
            {
                min                             2.4
                max                             2.9
            }
            velocity                            dyn_random
            {
                min                             160
                max                             180
            }
            all_particle_dimensions             dyn_random
            {
                min                             80
                max                             120
            }
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_height                          1
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.104348  0.0784314 0.0784314 0.0784314 0.894118
            time_colour                         0.708696  0 0 0 0.694118
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector15
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -180
                max                             180
            }
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             2
            }
        }
        affector                                TextureAnimator Affector12
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
    technique sparks
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks
        {
            emission_rate                       33
            time_to_live                        dyn_random
            {
                min                             2.5
                max                             3
            }
            velocity                            dyn_random
            {
                min                             250
                max                             300
            }
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             6
            }
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           150
            box_height                          1
            box_depth                           150
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.11087  1 1 1 1
            time_colour                         0.758696  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                Scale Affector14
        {
            xyz_scale                           -3
        }
    }
    technique flash
    {
        visual_particle_quota                   6
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_02
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       6
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.8
            }
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             450
                max                             700
            }
            position                            0 8 0
            colour                              1 0.501961 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.3  0 0.501961 1 1
            time_colour                         0.5  0 0.501961 1 1
            time_colour                         1    0 0 0 1
        }
    }
    technique fire_refract
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_noise_01
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_rotation_type             vertex
        }
        emitter                                 Box fire_add1
        {
            emission_rate                       5
            angle                               5
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             160
                max                             180
            }
            all_particle_dimensions             dyn_random
            {
                min                             100
                max                             150
            }
            position                            0 130 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_height                          1
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.506522  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
}
