system rift/flamer_fire_burning_small
{
    fixed_timeout                               7
    nonvisible_update_timeout                   1
    scale_velocity                              0.006
    scale                                       0.006 0.006 0.006
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 3
    technique fire_alpha2
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/explosion_and_smoke_anim_01
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box fire_alpha
        {
            angle                               5
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             200
                max                             300
            }
            duration                            6
            all_particle_dimensions             dyn_random
            {
                min                             150
                max                             200
            }
            position                            0 100 0
            direction                           0.5 1 0
            box_width                           150
            box_height                          150
            box_depth                           150
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.2  0.3 0.3 0.3 1
            time_colour                         0.804348  0.3 0.3 0.3 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector15
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0
                max                             1
            }
        }
        affector                                TextureAnimator Affector12
        {
            end_texture_coords_range            20
            texture_start_random                false
        }
    }
    technique fire_alpha3
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_anim_01
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 2
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box fire_alpha
        {
            angle                               5
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             200
                max                             300
            }
            duration                            6
            all_particle_dimensions             dyn_random
            {
                min                             200
                max                             300
            }
            position                            0 100 0
            direction                           0.5 1 0
            box_width                           150
            box_height                          150
            box_depth                           150
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.145652  0.3 0.3 0.3 1
            time_colour                         0.806522  0.3 0.3 0.3 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector15
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0
                max                             2
            }
        }
        affector                                TextureAnimator Affector12
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
    }
    technique sparks
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks
        {
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             300
                max                             400
            }
            duration                            6
            all_particle_dimensions             dyn_random
            {
                min                             5
                max                             7
            }
            position                            0 200 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           150
            box_height                          150
            box_depth                           150
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.606522  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique 
    {
        position                                0 10 0
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            angle                               5
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             200
                max                             300
            }
            duration                            6
            particle_width                      dyn_random
            {
                min                             150
                max                             200
            }
            particle_height                     dyn_random
            {
                min                             150
                max                             200
            }
            position                            0 160 0
            direction                           0.5 1 0
            start_colour_range                  0.392157 0.745098 0 1
            end_colour_range                    0.235294 0.501961 0 1
            box_width                           150
            box_height                          150
            box_depth                           150
        }
        affector                                Colour 
        {
            time_colour                         0    0.266667 0.266667 0.266667 0
            time_colour                         0.204348  0.27451 0.27451 0.27451 1
            time_colour                         0.702174  0 0 0 0.8
            time_colour                         1    0 0 0 0
        }
        affector                                TextureAnimator Affector12
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                TextureRotator Affector7
        {
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -1
                max                             1
            }
        }
    }
}
