system rift/gnerot_stomp
{
    fixed_timeout                               1
    nonvisible_update_timeout                   1
    scale_velocity                              0.012
    scale                                       0.012 0.012 0.012
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 50
    technique ring
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_hit_circle_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 0.494118
            time_colour                         1    0 0 0 0
        }
    }
    technique smoke_ring
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle smoke_ring
        {
            emission_rate                       200
            angle                               15
            time_to_live                        dyn_random
            {
                min                             0.35
                max                             0.4
            }
            velocity                            dyn_random
            {
                min                             800
                max                             900
            }
            all_particle_dimensions             dyn_random
            {
                min                             125
                max                             150
            }
            position                            0 10 0
            auto_direction                      true
            force_emission                      true
            radius                              1
        }
        affector                                Colour 
        {
            time_colour                         0    0.239216 0.239216 0.176471 0
            time_colour                         0.1  0.239216 0.239216 0.176471 0.447059
            time_colour                         0.708696  0.231373 0.231373 0.164706 0.447059
            time_colour                         1    0.239216 0.239216 0.176471 0
        }
        affector                                TextureAnimator Affector25
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
    technique sparks
    {
        visual_particle_quota                   25
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_type                      oriented_self
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               84
            time_to_live                        dyn_random
            {
                min                             1
                max                             1
            }
            velocity                            dyn_random
            {
                min                             500
                max                             750
            }
            particle_width                      3
            particle_height                     dyn_random
            {
                min                             3
                max                             25
            }
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.74902 0.74902 0.74902 1
            time_colour                         1    0.74902 0.74902 0.74902 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
    }
    technique lines
    {
        visual_particle_quota                   25
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_i
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      150
            particle_height                     dyn_random
            {
                min                             150
                max                             300
            }
            end_texture_coords_range            3
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.247059 0 0.494118
            time_colour                         1    0.501961 0.247059 0 0
        }
    }
    technique debris
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       100
            angle                               60
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             500
                max                             1500
            }
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             20
            }
            position                            0 10 0
            end_texture_coords_range            15
            colour                              0.313726 0.313726 0.313726 1
            force_emission                      true
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -1500 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector212
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
        }
    }
    technique ring
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.4
            velocity                            0
            duration                            0.4
            all_particle_dimensions             100
            position                            0 10 0
        }
        affector                                Scale Affector20
        {
            xyz_scale                           2500
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
}
