system rift/granan_acid_spit
{
    keep_local                                  true
    fixed_timeout                               0.6
    nonvisible_update_timeout                   1
    scale_velocity                              0.13
    scale                                       0.13 0.13 0.13
    tight_bounding_box                          true
    category                                    RIFT
    cache_count                                 20
    technique 1
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fluid_glowing_green_anim_8x4
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 4
            texture_coords_columns              8
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point Emitter1
        {
            angle                               30
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             20
                max                             45
            }
            particle_width                      dyn_random
            {
                min                             4
                max                             12
            }
            particle_height                     dyn_random
            {
                min                             30
                max                             60
            }
            position                            -10 0 0
            direction                           1 0 0
            end_texture_coords_range            20
            colour                              0.188235 0.188235 0.188235 1
            force_emission                      true
        }
        affector                                Colour Affector24
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique 2
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fluid_glowing_green_anim_8x4
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 4
            texture_coords_columns              8
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point Emitter1
        {
            angle                               25
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             2
                max                             4
            }
            all_particle_dimensions             20
            position                            -10 0 0
            direction                           1 0 0
            end_texture_coords_range            20
            colour                              0.188235 0.188235 0.188235 1
            force_emission                      true
        }
        affector                                Colour Affector24
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
}
