system player/green/green_spaceship_exhaust
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.0050
    scale                                       0.0050 0.0050 0.0050
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 4
    technique trail1
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_explosion_flame_02
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point trail1
        {
            emission_rate                       100
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            velocity                            1
            particle_width                      50
            particle_height                     50
            keep_local                          true
            direction                           -1 0 0
        }
        affector                                Scale 
        {
            x_scale                             -100
            y_scale                             500
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.61087  0 0.25098 0 1
            time_colour                         1    0 0 0 0
        }
    }
    technique flare
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_woosh_glow_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       100
            time_to_live                        0.1
            velocity                            0.0001
            all_particle_dimensions             200
            keep_local                          true
            colour                              0 0.25098 0 1
        }
        affector                                TextureRotator Affector90
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -2
                max                             2
            }
            rotation_speed                      0
        }
    }
}
