system player/green/green_spaceship_shield
{
    keep_local                                  true
    fixed_timeout                               5
    nonvisible_update_timeout                   1
    scale_velocity                              0.0400
    scale                                       0.0400 0.0400 0.0400
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 2
}
