system player/green/green_emp_change
{
    fixed_timeout                               0.5
    nonvisible_update_timeout                   1
    scale_velocity                              0.0200
    scale                                       0.0200 0.0200 0.0200
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 2
    technique flash2
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lensflare_depth_off
        renderer                                Billboard
        {
            render_queue_group                  68
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            emission_rate                       1000
            time_to_live                        0.3
            velocity                            0
            all_particle_dimensions             1
            keep_local                          true
            colour                              0.776471 0.388235 0 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           5000
        }
        affector                                Colour 
        {
            time_colour                         0    0.156863 0.501961 0 1
            time_colour                         1    0 0 0 0
        }
    }
    technique flash2
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  68
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.35
            velocity                            0
            all_particle_dimensions             1
            keep_local                          true
            colour                              0.776471 0.388235 0 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           3000
        }
        affector                                Colour 
        {
            time_colour                         0    0.156863 0.501961 0 1
            time_colour                         1    0 0 0 0
        }
    }
    technique flare2
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_nocolor
        renderer                                Billboard
        {
            render_queue_group                  67
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             1
            keep_local                          true
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.506522  0.156863 0.501961 0 1
            time_colour                         1    0.0784314 0.247059 0 0
        }
    }
    technique ring3
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            emission_rate                       1000
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             1
            keep_local                          true
            colour                              0.776471 0.388235 0 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1000
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0.898039
            time_colour                         0.508696  1 1 1 0.898039
            time_colour                         1    1 1 1 0
        }
    }
}
