system player/green/green_debris_trail
{
    fixed_timeout                               2
    nonvisible_update_timeout                   1
    scale_velocity                              0.0500
    scale                                       0.0500 0.0500 0.0500
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 100
    technique fire_alpha
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_spark_rectangle_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            angle                               45
            time_to_live                        1
            velocity                            dyn_random
            {
                min                             10
                max                             50
            }
            duration                            dyn_random
            {
                min                             0.7
                max                             1
            }
            all_particle_dimensions             dyn_random
            {
                min                             1.5
                max                             3
            }
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           5
            box_height                          5
            box_depth                           5
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0.25098 0.25098 0.25098 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector6
        {
            rotation                            dyn_random
            {
                min                             -0.5
                max                             0.5
            }
            rotation_speed                      1
        }
        affector                                LinearForce Affector17
        {
            force_vector                        0 -100 0
        }
    }
    technique flash
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_spark_rectangle_01
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.3
            velocity                            0
            all_particle_dimensions             5
            colour                              0.12549 0.12549 0.12549 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           30
        }
        affector                                Colour Affector79
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
        }
    }
}
