system exor/laser_direction_pointer
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.0125
    scale                                       0.0125 0.0125 0.0125
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique add_flame_blue
    {
        keep_local                              true
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box add_flame_blue
        {
            emission_rate                       500
            angle                               1.5
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.2
            }
            velocity                            1
            particle_width                      dyn_random
            {
                min                             5
                max                             20
            }
            particle_height                     500
            position                            1500 0 0
            direction                           1 0 0
            colour                              0 0.192157 1 1
            box_width                           3000
            box_height                          1
            box_depth                           1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0.494118
            time_colour                         0.502174  0 0.333333 0.666667 1
            time_colour                         1    0 0 0 0.494118
        }
    }
}
