system rift/level_3
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.13
    scale                                       0.13 0.13 0.13
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 6
    technique fire_alpha
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/numbers
        renderer                                Billboard
        {
            render_queue_group                  66
            texture_coords_rows                 2
            texture_coords_columns              5
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       200
            angle                               0
            time_to_live                        1.5
            velocity                            0.0001
            all_particle_dimensions             7
            texture_coords                      3
            colour                              0 1 1 1
        }
    }
}
