system exor/light_blue
{
    nonvisible_update_timeout                   1
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 0
    technique flare
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/light_blue_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       1000
            angle                               0
            time_to_live                        10
            velocity                            0.0001
            all_particle_dimensions             2.5
        }
    }
}
