system rift/magnetic_rock_radius
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.02
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 15
    technique sparksgravity
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_violet_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Circle DebrisEmitter
        {
            emission_rate                       200
            angle                               1
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      dyn_random
            {
                min                             12
                max                             15
            }
            particle_height                     dyn_random
            {
                min                             25
                max                             45
            }
            position                            0 10 0
            keep_local                          true
            start_colour_range                  1 1 1 1
            radius                              1100
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0.0470588 0.0470588 0.0470588 0.109804
        }
        affector                                Gravity Affector70
        {
            position                            0 110 0
            mass_affector                       10000
            gravity                             50
        }
    }
    technique sparksgravity
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_violet_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box DebrisEmitter
        {
            emission_rate                       25
            angle                               1
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      dyn_random
            {
                min                             12
                max                             15
            }
            particle_height                     dyn_random
            {
                min                             25
                max                             45
            }
            position                            0 10 0
            keep_local                          true
            start_colour_range                  1 1 1 1
            box_width                           400
            box_height                          1
            box_depth                           400
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0.0470588 0.0470588 0.0470588 0.109804
        }
    }
}
