system rift/mech_mine_beacon_gravity
{
    nonvisible_update_timeout                   1
    scale                                       0.1 0.1 0.1
    tight_bounding_box                          true
    cache_count                                 50
    technique flare
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/light_violet_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       0.5
            angle                               0
            time_to_live                        0.5
            velocity                            0.0001
            all_particle_dimensions             30
        }
        affector                                Colour Affector13
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.502174  0.501961 0.501961 0.501961 0.498039
            time_colour                         1    0 0 0 0
        }
    }
}
