system rift/mech_dash_fire
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.03
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 40
    technique fire_alpha2
    {
        visual_particle_quota                   40
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_anim_01
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 8
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box fire_alpha1
        {
            angle                               dyn_random
            {
                min                             20
                max                             60
            }
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             1.2
            }
            velocity                            dyn_random
            {
                min                             20
                max                             80
            }
            all_particle_dimensions             dyn_random
            {
                min                             40
                max                             80
            }
            position                            0 40 0
            box_width                           40
            box_height                          1
            box_depth                           40
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.251223  0.3 0.3 0.3 0.44484
            time_colour                         0.806522  0.3 0.3 0.3 0.494662
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector15
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.4
                max                             0.4
            }
        }
        affector                                TextureAnimator Affector12
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                Scale Affector148
        {
            xyz_scale                           30
        }
        affector                                LinearForce Affector34
        {
            force_vector                        0 10 0
        }
    }
    technique sparks
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks1
        {
            angle                               60
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             1
            }
            velocity                            dyn_random
            {
                min                             100
                max                             150
            }
            duration                            6
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             4
            }
            position                            0 5 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           40
            box_height                          1
            box_depth                           40
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.11087  1 1 1 1
            time_colour                         0.708696  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce Affector23
        {
            force_vector                        0 50 0
        }
    }
    technique fire_alpha2
    {
        visual_particle_quota                   40
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_anim_01
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 8
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box fire_alpha2
        {
            angle                               dyn_random
            {
                min                             20
                max                             60
            }
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             1.2
            }
            velocity                            dyn_random
            {
                min                             20
                max                             80
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             40
            }
            position                            0 20 0
            box_width                           75
            box_height                          1
            box_depth                           75
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.246928  0.3 0.3 0.3 0.47331
            time_colour                         0.806522  0.3 0.3 0.3 0.476868
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector15
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.4
                max                             0.4
            }
        }
        affector                                TextureAnimator Affector12
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                Scale Affector95
        {
            xyz_scale                           50
        }
        affector                                LinearForce Affector21
        {
            force_vector                        0 10 0
        }
    }
}
