system rift/mech_jump_portal_exit
{
    fixed_timeout                               1.8
    nonvisible_update_timeout                   1
    scale_velocity                              0.02
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    cache_count                                 5
    technique 
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_nocolor_add_atlas
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_columns              4
            billboard_type                      oriented_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
        }
        emitter                                 Box 
        {
            emission_rate                       25
            time_to_live                        1.2
            duration                            0.5
            particle_width                      50
            particle_height                     dyn_random
            {
                min                             1000
                max                             1200
            }
            direction                           0 0 0
            end_texture_coords_range            3
            colour                              0 0.501961 1 1
            box_width                           200
            box_height                          1
            box_depth                           200
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.102174  1 1 1 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            x_scale                             dyn_random
            {
                min                             1000
                max                             1200
            }
        }
    }
    technique rings_grow
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_add_02
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       200
            angle                               0
            time_to_live                        0.7
            velocity                            1
            all_particle_dimensions             1
            position                            0 50 0
            colour                              1 0.501961 0 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.5  0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      dyn_random
            {
                min                             -5
                max                             5
            }
        }
        affector                                Scale Affector110
        {
            xyz_scale                           1000
        }
    }
    technique rings_shrink
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_add_02
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       200
            angle                               0
            time_to_live                        0.7
            velocity                            1
            all_particle_dimensions             500
            position                            0 50 0
            colour                              1 0.501961 0 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.3  0 0.501961 1 1
            time_colour                         0.5  0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      dyn_random
            {
                min                             -5
                max                             5
            }
        }
        affector                                Scale Affector110
        {
            xyz_scale                           -1500
        }
    }
    technique ball
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_02
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       20
            angle                               360
            time_to_live                        0.5
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             1
            position                            0 50 0
            colour                              0.262745 0.937255 0.870588 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
        affector                                Scale Affector24
        {
            xyz_scale                           1000
        }
    }
    technique glow
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       100
            angle                               360
            time_to_live                        0.5
            velocity                            1
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             2
            }
            position                            0 50 0
            colour                              0.262745 0.937255 0.870588 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
        affector                                Scale Affector25
        {
            xyz_scale                           1000
        }
    }
    technique directional_refract
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point refract
        {
            emission_rate                       2
            angle                               0
            time_to_live                        1
            velocity                            0.1
            all_particle_dimensions             1
            position                            0 50 0
            direction                           1 0 0
            colour                              0 1 1 1
            force_emission                      true
        }
        affector                                Colour Affector197
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.0478261  1 1 1 1
            time_colour                         0.256522  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                Scale Affector9
        {
            xyz_scale                           2500
        }
    }
    technique shockwave_single
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/bomb_shockwave_atlas_01
        renderer                                Billboard
        {
            texture_coords_rows                 8
            texture_coords_columns              8
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            emission_rate                       1.5
            time_to_live                        1.2
            velocity                            0
            all_particle_dimensions             700
            position                            0 50 0
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureAnimator Affector71
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                TextureRotator Affector37
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
    }
    technique flash2
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_nodepth_02
        renderer                                Billboard
        {
            render_queue_group                  66
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.3
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            start_colour_range                  1 1 0.50196 1
            end_colour_range                    1 0.501961 0.25098 1
            colour                              1 0.501961 0 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           10000
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 1
        }
    }
}
