system rift/mech_footstep_wet_ground
{
    fixed_timeout                               1.5
    nonvisible_update_timeout                   1
    scale_velocity                              0.02
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 10
    technique debris
    {
        position                                0 5 0
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box DebrisEmitter
        {
            emission_rate                       500
            angle                               70
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             400
                max                             600
            }
            particle_width                      dyn_random
            {
                min                             8
                max                             16
            }
            particle_height                     dyn_random
            {
                min                             30
                max                             60
            }
            end_texture_coords_range            15
            colour                              0.32549 0.160784 0 1
            force_emission                      true
            box_width                           50
            box_height                          50
            box_depth                           50
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0.8
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
        affector                                LinearForce 
        {
            force_vector                        0 -1200 0
        }
    }
    technique ring2
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_noise_01
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.6
            }
            velocity                            0
            all_particle_dimensions             100
            position                            0 1 0
            colour                              0.0627451 0.0627451 0.0627451 1
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           200
        }
        affector                                TextureRotator Affector120
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -5
                max                             5
            }
            rotation_speed                      dyn_random
            {
                min                             -0.1
                max                             0.1
            }
        }
        affector                                Colour Affector23
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.506522  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
}
