system rift/mech_plasma_gun_projectile_hit
{
    fixed_timeout                               0.6
    nonvisible_update_timeout                   1
    scale_velocity                              0.0075
    scale                                       0.0075 0.0075 0.0075
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 50
    technique core
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_explosion_01
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_rotation_type             vertex
        }
        emitter                                 Box Emitter1
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             0
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             100
                max                             260
            }
            position                            0 50 0
            force_emission                      true
            box_width                           75
            box_height                          75
            box_depth                           75
        }
        affector                                Colour Affector35
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
        affector                                TextureRotator Affector7
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
        affector                                Scale Affector27
        {
            xyz_scale                           dyn_curved_linear
            {
                control_point                   0.1 0
                control_point                   0.4 0
                control_point                   1 -300
            }
        }
    }
    technique sparks
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      oriented_self
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.6
            }
            velocity                            dyn_random
            {
                min                             500
                max                             800
            }
            particle_width                      7
            particle_height                     dyn_random
            {
                min                             10
                max                             100
            }
            position                            0 50 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 0.698039
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
    }
    technique lines
    {
        enabled                                 false
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_flash_i_add
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.4
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      20
            particle_height                     dyn_random
            {
                min                             150
                max                             250
            }
            position                            0 50 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0.501961 1 1
            time_colour                         1    0 0 0 1
        }
    }
    technique ring
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_shockwave_a_add
        renderer                                Billboard
        {
            render_queue_group                  62
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.3
            velocity                            0
            all_particle_dimensions             200
            position                            0 50 0
            colour                              1 1 1 0.2
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1000
        }
        affector                                Colour Affector22
        {
            time_colour                         0    0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique refract
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.3
            velocity                            0
            all_particle_dimensions             100
            position                            0 50 0
            colour                              1 1 1 0.2
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1000
        }
        affector                                Colour Affector23
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.502174  1 1 1 0.698039
            time_colour                         1    1 1 1 0
        }
    }
}
