system rift/mega_rift_dynamo
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 30
    technique sparks_gravity_sphere_1
    {
        keep_local                              true
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface DebrisEmitter
        {
            emission_rate                       500
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             5
                max                             10
            }
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             1.5
            }
            keep_local                          true
            start_colour_range                  1 1 1 1
            radius                              13
        }
        affector                                Colour 
        {
            time_colour                         0    0.054902 0.054902 0.054902 0.494118
            time_colour                         0.330435  1 1 1 1
            time_colour                         0.663043  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                Vortex 
        {
            rotation_axis                       0 -1 0
            rotation_speed                      5
        }
    }
    technique sparks_gravity_sphere_2
    {
        keep_local                              true
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_bolt_4x4_blue_01
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Circle DebrisEmitter
        {
            emission_rate                       50
            angle                               1
            time_to_live                        0.3
            velocity                            1
            particle_width                      70
            particle_height                     70
            position                            0 1 0
            keep_local                          true
            end_texture_coords_range            15
            start_colour_range                  1 1 1 1
            auto_direction                      true
            radius                              1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation_speed                      0
        }
    }
}
