system rift/meteor_trail
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.03
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 10
    technique smoke_trail
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/explosion_and_darksmoke_anim_01
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Point trail
        {
            emission_rate                       200
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            1
            all_particle_dimensions             dyn_random
            {
                min                             75
                max                             100
            }
            position                            30 0 0
            direction                           -1 0 0
            end_texture_coords_range            63
        }
        affector                                Scale 
        {
            xyz_scale                           -50
        }
        affector                                Colour 
        {
            time_colour                         0    0.972549 0.972549 0.94902 0.4
            time_colour                         0.104348  0.501961 0.501961 0.501961 0.8
            time_colour                         0.502689  0.247059 0.247059 0.247059 0.709804
            time_colour                         1    0.121569 0.121569 0.121569 0
        }
        affector                                TextureAnimator Affector185
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                TextureRotator Affector186
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             0.3
            }
        }
    }
    technique sparks
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       50
            angle                               30
            time_to_live                        dyn_random
            {
                min                             1.5
                max                             2
            }
            velocity                            dyn_random
            {
                min                             20
                max                             30
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             4
            }
            direction                           -1 0 0
            box_width                           50
            box_height                          50
            box_depth                           50
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
        affector                                Scale Affector21
        {
            xyz_scale                           -1
        }
    }
    technique refract
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_noise_01
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 SphereSurface flash2
        {
            emission_rate                       20
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            20
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             40
            }
            auto_direction                      true
            radius                              60
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.5  0.261017 0.261017 0.261017 0.230508
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector120
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.2
                max                             0.3
            }
        }
        affector                                Scale Affector121
        {
            xyz_scale                           dyn_random
            {
                min                             100
                max                             200
            }
        }
        affector                                Gravity Affector70
        {
            mass_affector                       10000
            gravity                             0.6
        }
    }
    technique sparksgravity
    {
        keep_local                              true
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      2
            particle_height                     dyn_random
            {
                min                             3
                max                             4
            }
            start_colour_range                  1 1 1 1
            radius                              40
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.500977  1 1 1 0.752811
            time_colour                         1    0 0 0 0
        }
        affector                                Gravity Affector70
        {
            mass_affector                       10000
            gravity                             3
        }
    }
    technique sparks_2
    {
        enabled                                 false
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_anim_01
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 8
            texture_coords_columns              4
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 SphereSurface flash2
        {
            emission_rate                       100
            angle                               1
            time_to_live                        1
            velocity                            dyn_random
            {
                min                             10
                max                             20
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             40
            }
            end_texture_coords_range            31
            colour                              0.776471 0.388235 0 1
            auto_direction                      true
            radius                              30
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.253639  0.494915 0.494915 0.494915 0.515254
            time_colour                         1    0 0 0 0
        }
        affector                                TextureAnimator 
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                TextureRotator 
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      1
        }
    }
}
