system rift/migrating_birds
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.05
    scale                                       0.05 0.05 0.05
    tight_bounding_box                          true
    category                                    RIFT
    cache_count                                 30
    technique 
    {
        visual_particle_quota                   2000
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/bird_anim
        renderer                                Billboard
        {
            texture_coords_columns              8
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       500
            angle                               45
            time_to_live                        dyn_random
            {
                min                             3
                max                             5
            }
            velocity                            dyn_random
            {
                min                             25
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             25
            }
            position                            500 -400 0
            direction                           1 0 1
            end_texture_coords_range            5
            start_colour_range                  1 1 1 1
            end_colour_range                    0 0 0 1
            box_width                           2500
            box_height                          200
            box_depth                           2500
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.11087  1 1 1 1
            time_colour                         0.921739  1 1 1 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
        affector                                TextureAnimator Affector64
        {
            time_step                           0.07
            end_texture_coords_range            7
        }
        affector                                LinearForce Affector65
        {
            force_vector                        100 0 100
        }
    }
}
