system rift/multiplayer_boost_activation
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.03
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 5
    technique refract
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_noise_01
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 SphereSurface flash2
        {
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             20
            }
            position                            0 70 0
            force_emission                      true
            radius                              100
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.5  1 1 1 0.498039
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector120
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.2
                max                             0.3
            }
        }
        affector                                Scale Affector121
        {
            xyz_scale                           dyn_random
            {
                min                             100
                max                             200
            }
        }
    }
    technique sparks
    {
        visual_particle_quota                   250
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface sparks
        {
            emission_rate                       300
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            0.1
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             2
            }
            position                            0 70 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            force_emission                      true
            radius                              100
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.503322  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
}
