system rift/nuclear_powerplant_steam
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.035
    scale                                       0.035 0.035 0.035
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    technique s2
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box s2
        {
            emission_rate                       7
            angle                               dyn_random
            {
                min                             5
                max                             10
            }
            time_to_live                        dyn_random
            {
                min                             3
                max                             3.5
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             100
            }
            direction                           0.4 1 0
            end_texture_coords_range            3
            start_colour_range                  1 1 1 1
            colour                              0 0 0 1
            box_width                           30
            box_height                          30
            box_depth                           30
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.3  1 1 1 0.4
            time_colour                         0.86087  1 1 1 0.4
            time_colour                         1    1 1 1 0
        }
        affector                                Scale 
        {
            xyz_scale                           15
        }
        affector                                TextureRotator Affector104
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             0.2
            }
        }
    }
}
