system exor/paradrop_units_marker
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.0300
    scale                                       0.0300 0.0300 0.0300
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 0
    technique rings_alpha_1
    {
        visual_particle_quota                   3
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       5
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             200
                max                             250
            }
            position                            0 10 0
            colour                              1 0.501961 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.3  0.501961 0.501961 0.501961 1
            time_colour                         0.5  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      dyn_random
            {
                min                             1
                max                             3
            }
        }
    }
    technique rings_alpha_2
    {
        visual_particle_quota                   4
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_add_02
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       2
            angle                               0
            time_to_live                        1.6
            velocity                            125
            all_particle_dimensions             60
            position                            0 250 0
            direction                           0 -1 0
            colour                              1 0.501961 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.3  0 0.501961 1 1
            time_colour                         0.5  0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      dyn_random
            {
                min                             1
                max                             3
            }
        }
        affector                                Scale Affector15
        {
            xyz_scale                           70
        }
    }
    technique glow
    {
        visual_particle_quota                   3
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_nocolor
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       5
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            0
            all_particle_dimensions             50
            position                            0 10 0
            colour                              1 0.501961 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.3  0 0.501961 1 1
            time_colour                         0.5  0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      dyn_random
            {
                min                             -3
                max                             3
            }
        }
    }
}
