system rift/planet_marker_selected
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.007
    scale                                       0.007 0.007 0.007
    tight_bounding_box                          true
    category                                    RIFT
    cache_count                                 1
    technique rings_alpha_3
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_02_small_orange
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       100
            angle                               0
            time_to_live                        10000
            velocity                            0.001
            all_particle_dimensions             60
            position                            0 1 0
            colour                              0.752941 0.752941 0.752941 1
            force_emission                      true
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      5
        }
    }
    technique rings_alpha_3
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_02_small_orange
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       100
            angle                               0
            time_to_live                        10000
            velocity                            0.001
            all_particle_dimensions             80
            position                            0 1 0
            colour                              0.501961 0.501961 0.501961 1
            force_emission                      true
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      3
        }
    }
    technique rings_alpha_3
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_02_small_orange
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       100
            angle                               0
            time_to_live                        10000
            velocity                            0.001
            all_particle_dimensions             100
            position                            0 1 0
            colour                              0.25098 0.25098 0.25098 1
            force_emission                      true
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      1
        }
    }
}
