system rift/poogret_light_cone
{
    keep_local                                  true
    fixed_timeout                               5
    nonvisible_update_timeout                   1
    scale_velocity                              0.05
    scale                                       0.05 0.05 0.05
    tight_bounding_box                          true
    category                                    RIFT
    cache_count                                 40
    technique piorun
    {
        keep_local                              true
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_mp2_debris_atlas_d
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       60
            angle                               2
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.5
            }
            velocity                            1
            duration                            5
            particle_width                      5
            particle_height                     dyn_random
            {
                min                             1
                max                             2
            }
            direction                           1 0 0
            end_texture_coords_range            3
            auto_direction                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.504348  1 1 1 1
            time_colour                         0.51087  1 1 1 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
        affector                                TextureRotator Affector18
        {
            use_own_rotation                    true
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
        affector                                Scale Affector29
        {
            y_scale                             dyn_random
            {
                min                             600
                max                             1000
            }
        }
    }
    technique box
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_spark_rectangle_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       140
            angle                               0
            time_to_live                        0.4
            velocity                            0.001
            duration                            5
            all_particle_dimensions             dyn_random
            {
                min                             5
                max                             25
            }
            direction                           0 -1 0
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.66087  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator 
        {
        }
    }
    technique flare
    {
        keep_local                              true
        visual_particle_quota                   3
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_02
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       100
            time_to_live                        0.1
            velocity                            0.0001
            duration                            5
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             30
            }
            colour                              0.271186 1 0 1
        }
    }
}
