system rift/poogret_poo_idle
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.05
    scale                                       0.05 0.05 0.05
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 5
    technique s2
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_noise_01
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface s2
        {
            angle                               dyn_random
            {
                min                             20
                max                             30
            }
            time_to_live                        dyn_random
            {
                min                             2
                max                             5
            }
            velocity                            dyn_random
            {
                min                             10
                max                             20
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             40
            }
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.100379  1 1 1 0.2
            time_colour                         0.86087  1 1 1 0.1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce 
        {
            force_vector                        0 10 0
        }
    }
    technique 
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        max_velocity                            100
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       20
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             5
            }
            velocity                            dyn_random
            {
                min                             5
                max                             10
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            auto_direction                      true
            radius                              25
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.3  1 1 1 1
            time_colour                         0.7  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce Affector23
        {
            force_vector                        0 10 0
        }
    }
    technique 
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_orange
        max_velocity                            100
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       20
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             5
            }
            velocity                            dyn_random
            {
                min                             5
                max                             10
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            auto_direction                      true
            radius                              25
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.3  1 1 1 1
            time_colour                         0.7  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce Affector23
        {
            force_vector                        0 10 0
        }
    }
    technique 
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_violet_01
        max_velocity                            100
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       20
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             5
            }
            velocity                            dyn_random
            {
                min                             5
                max                             10
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            auto_direction                      true
            radius                              25
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.3  1 1 1 1
            time_colour                         0.7  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce Affector23
        {
            force_vector                        0 10 0
        }
    }
    technique s3
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface s2
        {
            angle                               dyn_random
            {
                min                             20
                max                             30
            }
            time_to_live                        dyn_random
            {
                min                             2
                max                             5
            }
            velocity                            dyn_random
            {
                min                             10
                max                             20
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             40
            }
            end_texture_coords_range            3
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0.80678 1 0
            time_colour                         0.100379  0 0.867797 1 0.2
            time_colour                         0.86087  0 0.867797 1 0.1
            time_colour                         1    0 0.989831 1 0
        }
        affector                                Scale 
        {
            xyz_scale                           5
        }
        affector                                LinearForce 
        {
            force_vector                        0 10 0
        }
    }
    technique s4
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface s2
        {
            angle                               dyn_random
            {
                min                             20
                max                             30
            }
            time_to_live                        dyn_random
            {
                min                             2
                max                             5
            }
            velocity                            dyn_random
            {
                min                             10
                max                             20
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             40
            }
            end_texture_coords_range            3
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 0.99661 0
            time_colour                         0.100379  1 0 0.99661 0.2
            time_colour                         0.86087  1 0 0.99661 0.2
            time_colour                         1    1 0 0.99661 0
        }
        affector                                Scale 
        {
            xyz_scale                           5
        }
        affector                                LinearForce 
        {
            force_vector                        0 10 0
        }
    }
    technique s5
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface s2
        {
            angle                               dyn_random
            {
                min                             20
                max                             30
            }
            time_to_live                        dyn_random
            {
                min                             2
                max                             5
            }
            velocity                            dyn_random
            {
                min                             10
                max                             20
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             40
            }
            end_texture_coords_range            3
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 0.894915 0 0
            time_colour                         0.100379  1 0.894915 0 0.2
            time_colour                         0.86087  1 0.915254 0 0.1
            time_colour                         1    1 0.915254 0 0
        }
        affector                                Scale 
        {
            xyz_scale                           5
        }
        affector                                LinearForce 
        {
            force_vector                        0 10 0
        }
    }
}
