system rift/power_well_drained
{
    keep_local                                  true
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.02
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 2
    technique refract_shockwave
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        1
            velocity                            0
            all_particle_dimensions             100
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           2800
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.854348  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique sparks_1
    {
        visual_particle_quota                   2000
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_type                      oriented_self
        }
        emitter                                 SphereSurface DebrisEmitter
        {
            emission_rate                       2000
            angle                               85
            time_to_live                        dyn_random
            {
                min                             1
                max                             3
            }
            velocity                            dyn_random
            {
                min                             650
                max                             900
            }
            particle_width                      3
            particle_height                     dyn_random
            {
                min                             3
                max                             25
            }
            start_colour_range                  1 1 1 1
            auto_direction                      true
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
    }
}
