system rift/power_fist_energy
{
    fixed_timeout                               1
    nonvisible_update_timeout                   1
    scale_velocity                              0.005
    scale                                       0.005 0.005 0.005
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 4
    technique sparks
    {
        keep_local                              true
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 SphereSurface DebrisEmitter
        {
            emission_rate                       250
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            velocity                            dyn_random
            {
                min                             10
                max                             20
            }
            duration                            0.2
            all_particle_dimensions             10
            position                            100 70 0
            direction                           -1 0 0
            start_colour_range                  1 1 1 1
            radius                              100
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
    }
    technique debris
    {
        keep_local                              true
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/metal_scrap_blue_anim
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface debris
        {
            emission_rate                       250
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             10
                max                             20
            }
            duration                            0.2
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             50
            }
            position                            100 70 0
            direction                           -1 0 0
            radius                              100
        }
        affector                                TextureAnimator Affector49
        {
            time_step                           0.04
            end_texture_coords_range            15
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector358
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    0.2 0.2 0.2 0
        }
    }
}
