system rift/power_jump_explosion_acid
{
    fixed_timeout                               1.5
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.03
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 2
    technique ring
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_hit_circle_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    0.0782919 1 0 0.494118
            time_colour                         1    0 0 0 0
        }
    }
    technique smoke_ring
    {
        visual_particle_quota                   150
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle smoke_ring
        {
            emission_rate                       200
            angle                               15
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             600
                max                             700
            }
            all_particle_dimensions             dyn_random
            {
                min                             125
                max                             150
            }
            position                            0 50 0
            auto_direction                      true
            force_emission                      true
            radius                              1
        }
        affector                                Colour 
        {
            time_colour                         0    0.185053 1 0 0
            time_colour                         0.1  0.313167 1 0 0.6
            time_colour                         0.500939  0.206406 1 0 0.603922
            time_colour                         1    0.483986 1 0 0
        }
        affector                                TextureAnimator Affector25
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
    technique lines
    {
        visual_particle_quota                   25
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_i
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      150
            particle_height                     dyn_random
            {
                min                             150
                max                             300
            }
            end_texture_coords_range            3
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.247059 0 0.494118
            time_colour                         1    0.501961 0.247059 0 0
        }
    }
    technique debris
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       100
            angle                               60
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             500
                max                             1500
            }
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             20
            }
            position                            0 10 0
            end_texture_coords_range            15
            colour                              0.313726 0.313726 0.313726 1
            force_emission                      true
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -1500 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector212
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.496264  1 1 1 1
            time_colour                         1    1 1 1 0
        }
    }
    technique sparks
    {
        visual_particle_quota                   40
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_spark_rectangle_01
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      oriented_self
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             500
                max                             1000
            }
            particle_width                      3
            particle_height                     dyn_random
            {
                min                             14
                max                             60
            }
            position                            0 50 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
    }
    technique sparks_1
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_spark_rectangle_01
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris_blood
        {
            emission_rate                       100
            angle                               60
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             250
                max                             500
            }
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             4
            }
            force_emission                      true
            box_width                           25
            box_height                          25
            box_depth                           25
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.470667  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -400 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
    }
    technique refract_shockwave
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        1
            velocity                            0
            all_particle_dimensions             100
            position                            0 5 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.752181  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique firealpha2
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_explosion_and_smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       500
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.7
            }
            velocity                            dyn_random
            {
                min                             0
                max                             400
            }
            all_particle_dimensions             dyn_random
            {
                min                             25
                max                             60
            }
            position                            0 15 0
            keep_local                          true
            end_texture_coords_range            31
            auto_direction                      true
            force_emission                      true
            radius                              10
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -0.22
                max                             0.22
            }
        }
        affector                                Colour Affector68
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                TextureAnimator Affector22
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                Scale 
        {
            xyz_scale                           -20
        }
    }
}
