system rift/power_rod_engine
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.04
    scale                                       0.04 0.04 0.04
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 1
    technique smoke
    {
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            render_queue_group                  64
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box s2
        {
            emission_rate                       200
            angle                               dyn_random
            {
                min                             2
                max                             6
            }
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             1
            }
            velocity                            dyn_random
            {
                min                             50
                max                             1000
            }
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             60
            }
            direction                           -1 0 0
            end_texture_coords_range            3
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            box_width                           10
            box_height                          10
            box_depth                           10
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.86087  0 0 0 0.783051
            time_colour                         1    0 0 0 0
        }
    }
    technique fireandsmoke
    {
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/explosion_and_smoke_blue_anim
        renderer                                Billboard
        {
            render_queue_group                  64
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box s2
        {
            emission_rate                       400
            angle                               1
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.6
            }
            velocity                            dyn_random
            {
                min                             50
                max                             1000
            }
            all_particle_dimensions             dyn_random
            {
                min                             15
                max                             30
            }
            direction                           -1 0 0
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            box_width                           10
            box_height                          10
            box_depth                           10
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.15  0.501961 0.501961 0.501961 0.94902
            time_colour                         1    0 0 0 0
        }
        affector                                TextureAnimator Affector90
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                TextureRotator Affector91
        {
            rotation                            dyn_random
            {
                min                             -0.5
                max                             0.5
            }
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             0.2
            }
        }
        affector                                Scale 
        {
            xyz_scale                           -60
        }
    }
    technique debris
    {
        visual_particle_quota                   1000
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_rotation_type             vertex
        }
        emitter                                 Box s2
        {
            emission_rate                       500
            angle                               dyn_random
            {
                min                             2
                max                             6
            }
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             1
            }
            velocity                            dyn_random
            {
                min                             50
                max                             1000
            }
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             3
            }
            direction                           -1 0 0
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            box_width                           40
            box_height                          40
            box_depth                           40
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0.294118
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
}
