system rift/power_rod_engine_flare
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.04
    scale                                       0.04 0.04 0.04
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 1
    technique debris
    {
        enabled                                 false
        visual_particle_quota                   1000
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_rotation_type             vertex
        }
        emitter                                 Circle s2
        {
            emission_rate                       500
            angle                               dyn_random
            {
                min                             2
                max                             6
            }
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             1
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             3
            }
            direction                           -1 0 0
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            radius                              20
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0.294118
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
        }
        affector                                LinearForce 
        {
            force_vector                        0 500 0
        }
    }
    technique flare
    {
        keep_local                              true
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_woosh_glow_01
        renderer                                Billboard
        {
            render_queue_group                  66
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       100
            time_to_live                        0.1
            velocity                            0.0001
            all_particle_dimensions             dyn_random
            {
                min                             70
                max                             110
            }
            colour                              0 0.522034 1 1
        }
        affector                                Colour Affector15
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.245652  1 1 1 1
            time_colour                         0.754348  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
        }
        affector                                Scale 
        {
            xyz_scale                           50
        }
    }
}
