system rift/power_rod_energy
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.09
    scale                                       0.09 0.09 0.09
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 10
    technique lightning_rod
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_bolt_4x4_blue_01
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       200
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            mass                                1.5
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             20
            }
            position                            75 0 0
            end_texture_coords_range            3
            box_width                           150
            box_height                          30
            box_depth                           30
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0.494118 0.494118 0.494118 0
            colour_operation                    multiply
        }
        affector                                TextureRotator Affector18
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
    }
    technique sparks
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.8
                max                             1
            }
            velocity                            dyn_random
            {
                min                             5
                max                             7
            }
            all_particle_dimensions             dyn_random
            {
                min                             0.5
                max                             1
            }
            position                            75 0 0
            start_colour_range                  1 1 1 1
            box_width                           150
            box_height                          30
            box_depth                           30
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         0.5  0.501961 0.501961 0.501961 1
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
    }
}
