system rift/rain_toxic
{
    nonvisible_update_timeout                   1
    disable_culling                             true
    scale_velocity                              0.025
    scale                                       0.025 0.025 0.025
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    technique 
    {
        visual_particle_quota                   750
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/blood_splat_nocolor_atlas
        default_particle_width                  8
        default_particle_height                 100
        default_particle_depth                  0
        renderer                                Billboard
        {
            texture_coords_columns              8
            billboard_type                      oriented_self
            billboard_origin                    top_center
        }
        emitter                                 Box 
        {
            emission_rate                       750
            angle                               3
            time_to_live                        1
            velocity                            2500
            position                            500 100 0
            direction                           0.2 -1 0
            end_texture_coords_range            5
            colour                              0.501961 1 0 0.392157
            box_width                           2500
            box_height                          1
            box_depth                           2500
        }
    }
}
