system exor/rep_explosion_test
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.2
    scale                                       0.2 0.2 0.2
    tight_bounding_box                          true
    category                                    SHOOTER
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion1
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion2
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            15 0 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion3
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            30 0 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha8x8
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion4
        renderer                                Billboard
        {
            texture_coords_rows                 8
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            45 0 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion5
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            60 0 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion6
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            0 15 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion7
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            15 15 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion8
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            30 15 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion9
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            45 15 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion12
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            15 30 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion13
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            30 30 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion15
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            60 30 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha12x6
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion17
        renderer                                Billboard
        {
            texture_coords_rows                 12
            texture_coords_columns              6
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            15 45 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            71
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha7x12
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion18
        renderer                                Billboard
        {
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            30 45 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
    technique fire_alpha14x6
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/rep_explosion19
        renderer                                Billboard
        {
            texture_coords_rows                 14
            texture_coords_columns              6
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       30
            angle                               1
            velocity                            dyn_random
            {
                min                             0.1
                max                             0.1
            }
            all_particle_dimensions             15
            position                            45 45 0
            colour                              0 0 0 0
            box_width                           1
            box_height                          1
            box_depth                           1
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 1
        }
    }
}
