system rift/rift_ball
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.015
    scale                                       0.015 0.015 0.015
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    technique sparks
    {
        visual_particle_quota                   250
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_spark_rectangle_01
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface sparks
        {
            emission_rate                       300
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            0.1
            all_particle_dimensions             dyn_random
            {
                min                             4
                max                             7
            }
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            radius                              150
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         0.606522  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
}
