system rift/spawner_canoptrix_blood_infinite
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 30
    technique blood
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fluid_no_color_anim_8x4
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       15
            angle                               40
            time_to_live                        1.5
            velocity                            dyn_random
            {
                min                             25
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             60
            }
            position                            0 5 0
            end_texture_coords_range            15
            start_colour_range                  1 0 0 1
            end_colour_range                    0.501961 0 0 1
            box_width                           20
            box_height                          20
            box_depth                           20
        }
        affector                                TextureRotator Affector6
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
        affector                                LinearForce Affector30
        {
            force_vector                        0 -50 0
        }
        affector                                Colour Affector79
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.102174  1 1 1 0.886275
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
        affector                                TextureAnimator Affector81
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
    }
}
