system rift/spawner_canoptrix_flies
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.08
    scale                                       0.08 0.08 0.08
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 15
    technique 
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/firefly_2x2
        max_velocity                            100
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       40
            angle                               0
            time_to_live                        dyn_random
            {
                min                             4
                max                             5
            }
            velocity                            dyn_random
            {
                min                             10
                max                             30
            }
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             5
            }
            position                            0 50 0
            box_width                           150
            box_depth                           150
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.2  0 0 0 1
            time_colour                         0.8  0 0 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                ForceField 
        {
            force                               50
            octaves                             3
            frequency                           4
            amplitude                           4
            persistence                         2
            worldsize                           1000 1000 1000
            movement                            0 0 0
            movement_frequency                  2
        }
    }
}
