system rift/sword_ribbon
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.13
    scale                                       0.13 0.13 0.13
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
}
