system exor/tank_boss_light_red_flash
{
    nonvisible_update_timeout                   1
    tight_bounding_box                          true
    category                                    SHOOTER
    cache_count                                 0
    technique flare
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/light_red_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       1000
            angle                               0
            time_to_live                        10
            velocity                            0.0001
            all_particle_dimensions             2.5
        }
    }
    technique flash
    {
        keep_local                              true
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/light_red_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       1000
            angle                               0
            time_to_live                        0.2
            velocity                            0.0001
            all_particle_dimensions             2.5
            force_emission                      true
        }
        affector                                Colour Affector2
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.1  1 1 1 1
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
        affector                                Scale Affector3
        {
            xyz_scale                           100
        }
    }
}
