system rift/tornado_fire
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 1
    technique s2
    {
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_anim_01
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 2
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box s2
        {
            emission_rate                       500
            angle                               dyn_random
            {
                min                             2
                max                             6
            }
            time_to_live                        dyn_random
            {
                min                             1
                max                             3
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            repeat_delay                        20
            all_particle_dimensions             dyn_random
            {
                min                             40
                max                             80
            }
            position                            0 100 0
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            auto_direction                      true
            box_width                           70
            box_height                          200
            box_depth                           70
        }
        affector                                Colour 
        {
            time_colour                         0    0.74902 0.74902 0.74902 0
            time_colour                         0.3  0.74902 0.74902 0.74902 0.15
            time_colour                         0.86087  0.74902 0.74902 0.74902 0.15
            time_colour                         1    0.74902 0.74902 0.74902 0
        }
        affector                                Vortex Affector16
        {
            rotation_axis                       0 1 0
            rotation_speed                      2
        }
        affector                                TextureAnimator Affector176
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation_speed                      dyn_random
            {
                min                             1
                max                             5
            }
        }
    }
    technique smoke_ground_wide
    {
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/fire_anim_01
        renderer                                Billboard
        {
            render_queue_group                  64
            texture_coords_rows                 2
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle s2
        {
            emission_rate                       500
            angle                               dyn_random
            {
                min                             2
                max                             6
            }
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             25
                max                             50
            }
            repeat_delay                        20
            all_particle_dimensions             dyn_random
            {
                min                             40
                max                             80
            }
            position                            0 50 0
            direction                           1 0 0
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            auto_direction                      true
            radius                              5
            emit_random                         false
        }
        affector                                Colour 
        {
            time_colour                         0    0.74902 0.74902 0.74902 0
            time_colour                         0.3  0.74902 0.74902 0.74902 0.15
            time_colour                         0.86087  0.74902 0.74902 0.74902 0.15
            time_colour                         1    0.74902 0.74902 0.74902 0
        }
        affector                                Vortex Affector16
        {
            rotation_axis                       0 1 0
            rotation_speed                      2
        }
        affector                                TextureAnimator Affector176
        {
            end_texture_coords_range            31
            texture_start_random                false
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation_speed                      dyn_random
            {
                min                             1
                max                             5
            }
        }
    }
    technique debris_ground
    {
        visual_particle_quota                   1000
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Circle s2
        {
            emission_rate                       2000
            angle                               90
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             25
                max                             50
            }
            repeat_delay                        20
            particle_width                      dyn_random
            {
                min                             3
                max                             6
            }
            particle_height                     dyn_random
            {
                min                             1
                max                             2
            }
            position                            0 50 0
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            auto_direction                      true
            radius                              30
            emit_random                         false
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 1
            time_colour                         0.86087  0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                Vortex Affector16
        {
            rotation_axis                       0 1 0
            rotation_speed                      2
        }
    }
    technique debris
    {
        visual_particle_quota                   1000
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_rotation_type             vertex
        }
        emitter                                 Box s2
        {
            emission_rate                       2000
            angle                               1
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            repeat_delay                        20
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             2
            }
            position                            0 100 0
            start_colour_range                  0.333333 0.333333 0.333333 1
            end_colour_range                    0.207843 0.207843 0.207843 1
            colour                              0 0 0 1
            auto_direction                      true
            box_width                           85
            box_height                          200
            box_depth                           85
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 1
            time_colour                         0.86087  0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                Vortex Affector16
        {
            rotation_axis                       0 1 0
            rotation_speed                      2
        }
    }
    technique swirl4
    {
        visual_particle_quota                   3
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/orange_vortex_01
        renderer                                Billboard
        {
            texture_coords_rows                 8
            texture_coords_columns              8
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            emission_rate                       2
            angle                               359
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             200
            position                            0 10 0
            keep_local                          true
            colour                              0.262745 0.937255 0.870588 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.2  0.0980392 0.0980392 0.0980392 0.8
            time_colour                         0.806522  0.0980392 0.0980392 0.0980392 0.8
            time_colour                         1    0 0 0 0
        }
        affector                                TextureAnimator Affector31
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
}
