system exor/tower_artillery_idle
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.1000
    scale                                       0.1000 0.1000 0.1000
    cache_count                                 0	
    tight_bounding_box                          true
    category                                    SHOOTER
    technique fire_alpha
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       5
            time_to_live                        1
            velocity                            dyn_random
            {
                min                             5
                max                             10
            }
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             16
            }
            direction                           1 0 0
            colour                              0 0 0 0
            box_width                           5
            box_height                          5
            box_depth                           5
        }
        affector                                TextureAnimator Affector13
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.184783  0.247059 0.247059 0.247059 0.8
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
        affector                                TextureRotator Affector6
        {
            rotation                            dyn_random
            {
                min                             -0.5
                max                             0.5
            }
            rotation_speed                      1
        }
        affector                                Scale Affector19
        {
            xyz_scale                           10
        }
        affector                                LinearForce Affector9
        {
            force_vector                        0 15 0
        }
    }
}
