system exor/tower_in_danger
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.0150
    scale                                       0.0150 0.0150 0.0150
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique rings_alpha_2
    {
        visual_particle_quota                   4
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_add_02
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       8
            angle                               0
            time_to_live                        0.8
            velocity                            500
            all_particle_dimensions             300
            position                            0 300 0
            keep_local                          true
            direction                           0 -1 0
            colour                              1 0.50196 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 0 0
            time_colour                         0.5  1 0 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      dyn_random
            {
                min                             3
                max                             -3
            }
        }
    }
    technique rings_alpha_3
    {
        visual_particle_quota                   4
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/alien_ring_add_02
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       8
            angle                               0
            time_to_live                        0.8
            velocity                            500
            all_particle_dimensions             300
            position                            0 5 0
            keep_local                          true
            colour                              1 0.501961 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 0 0
            time_colour                         0.5  1 0 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector10
        {
            mass_affector                       0
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             1
                max                             -1
            }
            rotation_speed                      dyn_random
            {
                min                             3
                max                             -3
            }
        }
    }
}
