system exor/tree_burned_destruction_small
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.0500
    scale                                       0.0500 0.0500 0.0500
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique smoke
    {
        visual_particle_quota                   8
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_cloud_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box smoke
        {
            emission_rate                       25
            angle                               85
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             40
                max                             50
            }
            all_particle_dimensions             dyn_random
            {
                min                             75
                max                             100
            }
            end_texture_coords_range            3
            start_colour_range                  0.501961 0.501961 0.25098 1
            end_colour_range                    0.501961 0.501961 0.50196 1
            force_emission                      true
            box_width                           50
            box_height                          175
            box_depth                           50
        }
        affector                                Colour 
        {
            time_colour                         0    1 0.905882 0.807843 0.6
            time_colour                         0.506522  1 0.807843 0.615686 0.4
            time_colour                         1    1 0.862745 0.72549 0
        }
        affector                                LinearForce Affector10
        {
            force_vector                        0 -40 0
        }
        affector                                Scale Affector19
        {
            xyz_scale                           70
            since_start_system                  true
        }
    }
    technique wood
    {
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/wood_splinter_atlas
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 Box debris
        {
            emission_rate                       50
            angle                               120
            velocity                            dyn_random
            {
                min                             400
                max                             550
            }
            particle_width                      dyn_random
            {
                min                             8
                max                             16
            }
            particle_height                     dyn_random
            {
                min                             10
                max                             20
            }
            end_texture_coords_range            3
            start_colour_range                  0.501961 0.501961 0.501961 1
            end_colour_range                    0.188235 0.188235 0.188235 1
            colour                              0 0.501961 0 1
            auto_direction                      true
            force_emission                      true
            box_width                           50
            box_height                          175
            box_depth                           50
        }
        affector                                LinearForce 
        {
            force_vector                        0 -700 0
        }
        affector                                TextureRotator Affector25
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -4
                max                             4
            }
        }
        affector                                Colour Affector47
        {
            time_colour                         0    0.501961 0.25098 0 1
            time_colour                         0.508696  0.501961 0.25098 0 1
            time_colour                         1    0.501961 0.25098 0 0
            colour_operation                    multiply
        }
    }
    technique sparks
    {
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_orange_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       50
            angle                               60
            time_to_live                        1.5
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             2
            }
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            force_emission                      true
            box_width                           20
            box_height                          175
            box_depth                           20
        }
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.25  1 1 1 0.709804
            time_colour                         0.408696  1 1 1 0.494118
            time_colour                         1    1 1 1 0
        }
        affector                                TextureRotator Affector6
        {
            rotation                            dyn_random
            {
                min                             -0.5
                max                             0.5
            }
            rotation_speed                      1
        }
        affector                                LinearForce Affector17
        {
            force_vector                        0 -100 0
        }
    }
}
