system exor/warcar_engine_rotator
{
    scale_velocity                              0.0050
    scale                                       0.0050 0.0050 0.0050
    tight_bounding_box                          true
    category                                    SHOOTER
    fade_out                                    true
    cache_count                                 0
    technique dust
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/light_red_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Circle DebrisEmitter
        {
            emission_rate                       100
            angle                               10
            time_to_live                        1
            velocity                            50
            particle_width                      dyn_random
            {
                min                             20
                max                             30
            }
            particle_height                     dyn_random
            {
                min                             20
                max                             30
            }
            keep_local                          true
            start_colour_range                  1 1 1 1
            radius                              235
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0.309804
            time_colour                         0.0543478  1 0 0 1
            time_colour                         0.958696  1 0 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                Vortex Affector387
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             1
                max                             2
            }
        }
    }
    technique rocks
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp2_debris_atlas_e
        renderer                                Billboard
        {
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Circle DebrisEmitter
        {
            emission_rate                       100
            angle                               10
            time_to_live                        1
            velocity                            50
            particle_width                      dyn_random
            {
                min                             5
                max                             30
            }
            particle_height                     dyn_random
            {
                min                             5
                max                             30
            }
            keep_local                          true
            end_texture_coords_range            7
            start_colour_range                  1 1 1 1
            radius                              235
        }
        affector                                Colour 
        {
            time_colour                         0    0.2 0.2 0.2 0.309804
            time_colour                         0.0478261  1 0 0 1
            time_colour                         0.958696  1 0 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                Vortex Affector387
        {
            rotation_axis                       0 1 0
            rotation_speed                      dyn_random
            {
                min                             1
                max                             2
            }
        }
    }
}
