system rift/acid_explosion_big_03
{
    fixed_timeout                               2
    nonvisible_update_timeout                   1
    scale_velocity                              0.024
    scale                                       0.024 0.024 0.024
    tight_bounding_box                          true
    category                                    RIFT
    cache_count                                 30
    technique firealpha2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/green_rep_explosion5
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 7
            texture_coords_columns              12
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       50
            angle                               80
            time_to_live                        dyn_random
            {
                min                             1.5
                max                             2
            }
            velocity                            dyn_random
            {
                min                             30
                max                             60
            }
            all_particle_dimensions             dyn_random
            {
                min                             220
                max                             276
            }
            position                            0 100 0
            force_emission                      true
            radius                              60
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.3
                max                             0.3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.22
                max                             0.22
            }
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            83
            texture_start_random                false
        }
        affector                                Colour Affector68
        {
            time_colour                         0    0.35 0.35 0.35 1
            time_colour                         0.5 0.35 0.35 0.35 1
            time_colour                         1    0.35 0.35 0.35 0
        }
    }
    technique sparks
    {
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_spark_rectangle_01
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             1
                max                             1
            }
            velocity                            dyn_random
            {
                min                             500
                max                             750
            }
            particle_width                      5
            particle_height                     dyn_random
            {
                min                             5
                max                             25
            }
            position                            0 25 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.752941 0.752941 0.752941 1
            time_colour                         0.5  0.752941 0.752941 0.752941 1
            time_colour                         1    0.752941 0.752941 0.752941 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
    }
    technique debris
    {
        visual_particle_quota                   15
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/metal_scrap_anim
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 2
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       100
            angle                               60
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             500
                max                             750
            }
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             50
            }
            position                            0 25 0
            colour                              0.313726 0.313726 0.313726 1
            force_emission                      true
        }
        affector                                TextureAnimator Affector49
        {
            time_step                           0.04
            end_texture_coords_range            15
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -800 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector358
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
    }
    technique lines
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/green_rep_trail5
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 17
            texture_coords_columns              5
            billboard_type                      oriented_self
            billboard_origin                    center_left
            billboard_rotation_type             vertex
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               100
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             50
                max                             100
            }
            particle_width                      dyn_random
            {
                min                             150
                max                             250
            }
            particle_height                     dyn_random
            {
                min                             20
                max                             60
            }
            end_texture_coords_range            84
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.5 0.5 0.5 1
            time_colour                         0.5 0.5 0.5 0.5 1
            time_colour                         1    0.5 0.5 0.5 0
        }
        affector                                TextureAnimator Affector45
        {
            end_texture_coords_range            84
            texture_start_random                false
        }
        affector                                TextureRotator Affector46
        {
            rotation                            -1.6
            rotation_speed                      0
        }
    }
    technique ring
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_01
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.7
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    0.603922 0.603922 0 1
            time_colour                         0.502174  0.592157 0.294118 0 1
            time_colour                         1    0 0 0 0
        }
    }
    technique refract_shockwave
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             100
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1500
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.5 0.5 0.5 0.5 0.5
            time_colour                         1    0 0 0 0
        }
    }
}
