system rift/blue_light_blink
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.0250
    scale                                       0.0250 0.0250 0.0250
    tight_bounding_box                          true
    category                                    RIFT
    cache_count                                 20
    technique flare
    {
        keep_local                              true
        visual_particle_quota                   3
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/light_blue_01
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       1
            angle                               0
            time_to_live                        1.25
            velocity                            0.0001
            all_particle_dimensions             40
        }
        affector                                Colour Affector13
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.5  0.501961 0.501961 0.501961 0.498039
            time_colour                         1    0 0 0 0
        }
    }
}
