system rift/gravity_projectile_trail_triangle_purple
{
    nonvisible_update_timeout                   3
    scale_velocity                              0.5
    scale                                       0.5 0.5 0.5
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 100
    
	technique flare
    {
        keep_local                              true
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_woosh_glow_01
        renderer                                Billboard
        {
            render_queue_group                  66
            billboard_rotation_type             vertex
        }
        emitter                                 Point flare
        {
            emission_rate                       100
            time_to_live                        0.1
            velocity                            0.0001
            all_particle_dimensions             dyn_random
            {
                min                             5
                max                             9
            }
            colour                              0.47451 0 0.27451 1
        }
        affector                                Colour Affector15
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.247826  1 1 1 1
            time_colour                         0.754348  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
	}
	
	technique ring
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/gravity_trail_triangle_purple_01
        renderer                                Billboard
        {
            render_queue_group                  62
        }
        emitter                                 Point flash2
        {
            time_to_live                        dyn_random
			{
                min                             0.0
                max                             0.8
            }
			
			emission_rate                       12000
            velocity                            0.0001
            all_particle_dimensions             0.5
			direction                           -1 0 0
            colour                              1 0.501961 0 10
        }
        affector                                Scale flash2
        {
            xyz_scale                           5
        }
        affector                                Colour Affector22
        {
            time_colour                         0    1 0.501961 0 1
            time_colour                         1    0 0 0 0
        }
		
		affector                                LinearForce Affector78
        {
            force_vector                        -25 0 0
        }
    }
	
	technique sparks_trail
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_purple_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
			billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       14000
            angle                               45
            time_to_live                        dyn_random
            {
                min                             0.0
                max                             0.8
            }
            velocity                            0.0001
            all_particle_dimensions             0.1
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
			position							-4 0 0
			direction                           -1 0 0
            box_width                           8
            box_height                          1
            box_depth                           1
        }
		
        affector                                Colour Affector26
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
        }
		
		affector                                Scale flash2
        {
            xyz_scale                           0.2
        }

		affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -4
                max                             4
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
		
		affector                                LinearForce Affector17
        {
            force_vector                        -20 0 0
        }
    }
}
