system rift/lipc_charging_maximum
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.01
    scale                                       0.01 0.01 0.01
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 2
    technique firealpha
    {
        visual_particle_quota                   130
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_explosion_water
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       100
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             5
                max                             12
            }
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             2
            }
            keep_local                          true
            box_width                           50
            box_height                          50
            box_depth                           50
        }
        affector                                Scale 
        {
            xyz_scale                           250
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -1
                max                             1
            }
        }
        affector                                Colour Affector68
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.508696  0.501961 0 0 0.694118
            time_colour                         1    0 0 0 0
        }
    }
    
    technique flash2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_nodepth_02
        renderer                                Billboard
        {
            render_queue_group                  65
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.35
            velocity                            0
            all_particle_dimensions             1
            keep_local                          true
            colour                              0.776471 0.388235 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                Scale Affector78
        {
            xyz_scale                           dyn_random
            {
                min                             1000
                max                             2000
            }
        }
    }
    technique flare2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/light_red_01
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             150
            }
            keep_local                          true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.508696  1 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                Scale Affector77
        {
            xyz_scale                           dyn_random
            {
                min                             250
                max                             500
            }
        }
    }
    technique laser
    {
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_rotation_type             vertex
            accurate_facing                     true
        }
        emitter                                 Box add_flame_blue
        {
            emission_rate                       3000
            angle                               0
            time_to_live                        0.1
            velocity                            1
            all_particle_dimensions             dyn_random
            {
                min                             25
                max                             50
            }
            position                            1750 0 0
            direction                           1 0 0
            colour                              1 0 0 1
            box_width                           3500
            box_height                          1
            box_depth                           1
        }
    }
    technique laser2
    {
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_rotation_type             vertex
            accurate_facing                     true
        }
        emitter                                 Box add_flame_blue
        {
            emission_rate                       3000
            angle                               0
            time_to_live                        0.1
            velocity                            1
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             120
            }
            position                            1750 0 0
            direction                           1 0 0
            colour                              1 0 0 1
            force_emission                      true
            box_width                           3500
            box_height                          1
            box_depth                           1
        }
    }
	
	technique lightning_directional_1
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_bolt_4x4_red_01
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    top_center
            billboard_rotation_type             vertex
        }
        emitter                                 Box add_flame_blue
        {
			emission_rate                       300
            angle                               180
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.4
            }
            velocity                            0.1
            all_particle_dimensions             dyn_random
            {
                min                             75
                max                             125
            }
            end_texture_coords_range            3
            colour                              0 1 1 1
            box_width                           20
            box_height                          20
            box_depth                           20
        }
        affector                                TextureRotator Affector168
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             -3.2
            }
            rotation_speed                      dyn_random
            {
                min                             -4
                max                             4
            }
        }
        affector                                Colour Affector197
        {
            time_colour                         0    0.5 0.5 0.5 1
            time_colour                         1    0.5 0.5 0.5 0
        }
    }
}
