system rift/morphium_emission_small
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.03
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    technique 
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       15
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             10
                max                             30
            }
            all_particle_dimensions             dyn_random
            {
                min                             4
                max                             5
            }
            box_height							22
            box_width                           22
            box_depth                           22
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.204348  1 1 1 1
            time_colour                         0.808696  1 1 1 1
            time_colour                         1    0 0 0 0
        }
		
		affector                                LinearForce Affector23
        {
            force_vector                        0 20 0
            force_application                   average
        }
    }
    technique 
    {
        visual_particle_quota                   30
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        max_velocity                            100
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       15
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             10
                max                             30
            }
            all_particle_dimensions             dyn_random
            {
                min                             4
                max                             5
            }
			position							30 0 0
			box_height							22
            box_width                           22
            box_depth                           22
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.204348  1 1 1 1
            time_colour                         0.808696  1 1 1 1
            time_colour                         1    0 0 0 0
        }
		
		affector                                LinearForce Affector23
        {
            force_vector                        0 -20 0
            force_application                   average
        }
    }
}
