system rift/plasma_emission_small
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.05
    scale                                       0.05 0.05 0.05
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 8
    
	technique piorun
    {
        keep_local                              true
        visual_particle_quota                   20
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_bolt_2x2_blue_01
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    top_center
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       10
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.4
            }
            velocity                            0.0001
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             20
            }
            direction                           1 0 0
			position							-1 0 0
            end_texture_coords_range            3
            auto_direction                      true
            radius                              1
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         0.1  0.501961 0.501961 0.501961 1
            time_colour                         1    0.501961 0.501961 0.501961 0
        }
        affector                                TextureRotator Affector18
        {
            use_own_rotation                    true
            rotation                            3.2
            rotation_speed                      0
        }
    }
	
	technique ring
    {
        keep_local                              true
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_circle_2x2_blue_02
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            emission_rate                       5
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.4
            }
            velocity                            0
            all_particle_dimensions             20
            end_texture_coords_range            3
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.15  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                TextureRotator Affector61
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
		
		affector                                Scale Affector31
        {
            xyz_scale                           10
        }
    }
}
