system rift/supercoolant_vent
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.05
    scale                                       0.05 0.05 0.05
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count									175
	
	technique water
    {
        position                                0 30 0
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/water_foam_01
        renderer                                Billboard
        {
            render_queue_group                  61
            texture_coords_rows                 8
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Circle water
        {
            angle                               10
            time_to_live                        dyn_random
            {
                min                             1.5
                max                             2.5
            }
            velocity                            dyn_random
            {
                min                             20
                max                             25
            }
            all_particle_dimensions             dyn_random
            {
                min                             75
                max                             100
            }
            colour                              0.992157 0.992157 0.984314 1
            radius                              25
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             0.5
            }
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.0978261  1 1 1 1
            time_colour                         0.61087  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                ScaleVelocity 
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0 -356.665
                control_point                   2 -0.983379
            }
            since_start_system                  true
        }
        affector                                Scale 
        {
            x_scale                             dyn_random
            {
                min                             50
                max                             100
            }
            y_scale                             dyn_random
            {
                min                             100
                max                             200
            }
        }
        affector                                LinearForce 
        {
            force_vector                        0 5 0
        }
        affector                                TextureAnimator Affector30
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
    }
	
    technique smoke_ring
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/smoke_anim_8x8_mild_blue
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              8
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Circle smoke_ring
        {
            emission_rate                       5
            angle                               1
            time_to_live                        dyn_random
            {
                min                             2
                max                             2.5
            }
            velocity                            dyn_random
            {
                min                             100
                max                             110
            }
            all_particle_dimensions             dyn_random
            {
                min                             25
                max                             75
            }
            position                            0 10 0
            auto_direction                      true
            radius                              6
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.5  1 1 1 0.14902
            time_colour                         1    1 1 1 0
        }
        affector                                TextureAnimator Affector25
        {
            time_step                           0.04
            end_texture_coords_range            31
        }
        affector                                TextureRotator Affector118
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.1
                max                             0.2
            }
        }
    }
	
    technique sparks
    {
        visual_particle_quota                   75
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks
        {
            emission_rate                       75
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             150
                max                             200
            }
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             3
            }
            position                            0 5 0
			direction							0 1 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           10
            box_height                          20
            box_depth                           10
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         0.606522  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
}
