system rift/time_damage_radiation
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.015
    scale                                       0.015 0.015 0.015
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
	cache_count                                 20
    technique sparks
    {
        visual_particle_quota                   75
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/green_spark_rectangle_01
        renderer                                Billboard
        {
            render_queue_group                  64
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks
        {
            emission_rate                       75
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             0.9
            }
            velocity                            dyn_random
            {
                min                             150
                max                             200
            }
            all_particle_dimensions             dyn_random
            {
                min                             3
                max                             6
            }
            position                            0 200 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            box_width                           250
            box_height                          250
            box_depth                           250
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         0.606522  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
	
	technique flash
    {
        visual_particle_quota                   6
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_02
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            emission_rate                       6
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.8
            }
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             100
                max                             150
            }
            position                            0 8 0
            colour                              1 0.501961 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.3  1 0.501961 0 1
            time_colour                         0.5  1 0.501961 0 1
            time_colour                         1    0 0 0 1
        }
    }
	
	technique smoke
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_noise_01
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       5
            angle                               25
            time_to_live                        dyn_random
            {
                min                             2
                max                             3
            }
            velocity                            dyn_random
            {
                min                             10
                max                             15
            }
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             50
            }
            position                            0 45 0
            start_colour_range                  0 0.501961 0 1
            end_colour_range                    1 1 1 1
            box_width                           50
            box_height                          10
            box_depth                           50
        }
        affector                                Colour Affector26
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.504348  1 0.501961 0 0.247059
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector6
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             2
                max                             -2
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
    }
}
