system rift/tower_crystal_blaster_hit_blue
{
    fixed_timeout                               1
    nonvisible_update_timeout                   1
    scale_velocity                              0.0075
    scale                                       0.0075 0.0075 0.0075
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 25
    
	technique sparks
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_blue_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             1
                max                             1
            }
            velocity                            dyn_random
            {
                min                             500
                max                             750
            }
            particle_width                      10
            particle_height                     dyn_random
            {
                min                             10
                max                             50
            }
            position                            0 100 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         1    0 0 0 0
        }
        affector                                ScaleVelocity Affector36
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0.00184502 72.5508
                control_point                   1 -1183.16
            }
            stop_at_flip                        true
        }
    }
    
	technique lines
    {
        visual_particle_quota                   10
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_explosion_flame_02
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
        }
        emitter                                 Point LinesEmitter
        {
            emission_rate                       100
            angle                               85
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             100
                max                             200
            }
            particle_width                      20
            particle_height                     dyn_random
            {
                min                             150
                max                             250
            }
            position                            0 100 0
            start_colour_range                  1 1 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 1 1 1
            time_colour                         1    0 0 0 1
        }
    }
    
	technique debris
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/metal_scrap_blue_anim
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              8
            billboard_rotation_type             vertex
        }
        emitter                                 Point debris
        {
            emission_rate                       200
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.7
                max                             1
            }
            velocity                            dyn_random
            {
                min                             0
                max                             750
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             60
            }
            position                            0 100 0
            colour                              0.313726 0.313726 0.313726 1
            force_emission                      true
        }
        affector                                TextureAnimator Affector49
        {
            time_step                           0.04
            end_texture_coords_range            15
        }
        affector                                LinearForce Affector50
        {
            force_vector                        0 -1000 0
        }
        affector                                TextureRotator Affector192
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.9
                max                             0.9
            }
            rotation_speed                      dyn_random
            {
                min                             -10
                max                             10
            }
        }
        affector                                Colour Affector223
        {
            time_colour                         0    0.12549 0.12549 0.12549 1
            time_colour                         0.506522  0.12549 0.12549 0.12549 1
            time_colour                         1    0.12549 0.12549 0.12549 0
        }
    }
    technique flare
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  65
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.3
            velocity                            0
            all_particle_dimensions             100
            position                            0 100 0
            colour                              1 0.85098 0 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1499
        }
        affector                                Colour Affector51
        {
            mass_affector                       0
            time_colour                         0    0.501961 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique refract
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             100
            position                            0 100 0
            colour                              1 1 1 0.2
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1499
        }
    }
	
	technique sparks
    {
        visual_particle_quota                   200
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      oriented_self
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       800
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             1000
                max                             1500
            }
            particle_width                      5
            particle_height                     dyn_random
            {
                min                             40
                max                             60
            }
            start_colour_range                  1 1 1 1
            force_emission                      true
			position                            0 100 0
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
	
	technique sparks
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_orange_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      oriented_self
        }
        emitter                                 Point DebrisEmitter
        {
            emission_rate                       200
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.5
            }
            velocity                            dyn_random
            {
                min                             600
                max                             800
            }
            particle_width                      5
            particle_height                     dyn_random
            {
                min                             40
                max                             60
            }
            start_colour_range                  1 1 1 1
            force_emission                      true
			position                            0 100 0
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
	
	 technique firealpha2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/explosion_and_smoke_blue_anim
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       200
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             1
            }
            velocity                            dyn_random
            {
                min                             60
                max                             120
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             50
            }
            force_emission                      true
            radius                              40
			position                            0 100 0
        }
        affector                                Scale 
        {
            xyz_scale                           250
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.4
                max                             0.4
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector68
        {
            time_colour                         0    0.501961 0.501961 0.501961 0.898039
            time_colour                         0.608696  0.121569 0.121569 0.121569 0.698039
            time_colour                         1    0.0666667 0.0666667 0.0666667 0
        }
    }
}
