system rift/tower_gravity_laser_charge
{
    nonvisible_update_timeout                   1
    scale_velocity                              0.02
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
	keep_local									true
	
	technique shockwave_flash
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/shockwave_dark_blue
        renderer                                Billboard
        {
            render_queue_group                  68
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.35
            velocity                            0
            all_particle_dimensions             1
            keep_local                          true
            colour                              0.776471 0.388235 0 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1000
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
	
	technique sparks_focus
    {
        visual_particle_quota                   300
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_purple_01
        renderer                                Billboard
        {
            billboard_type                      oriented_self
        }
        emitter                                 SphereSurface DebrisEmitter
        {
            emission_rate                       100
            angle                               1
            time_to_live                        0.8
            velocity                            dyn_random
            {
                min                             1
                max                             3
            }
            particle_width                      4
            particle_height                     dyn_random
            {
                min                             8
                max                             25
            }
            start_colour_range                  1 1 1 1
            radius                              150
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.0543478  0.2 0.2 0.2 1
            time_colour                         1    0 0 0 0
        }
        affector                                Gravity Affector70
        {
            mass_affector                       10000
            gravity                             5
        }
    }
	
	technique sphere_ring
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/shockwave_02
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       30
            angle                               360
			time_to_live						1
            velocity                            0
            all_particle_dimensions             70
            colour                              0.262745 0.937255 0.870588 1
        }

        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -5
                max                             5
            }
        }
    }
	
	technique sphere_refract
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_03
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       30
            angle                               360
			time_to_live						1
            velocity                            0
            all_particle_dimensions             100
            colour                              0.262745 0.937255 0.870588 1
        }

        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -5
                max                             5
            }
        }
    }
	
    technique core2
    {
        visual_particle_quota                   4
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/outer_glow
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       3
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1.5
                max                             2
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             100
            colour                              0.262745 0.937255 0.870588 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0.109804
            time_colour                         0.502174  0 0 0 1
            time_colour                         1    0 0 0 0.109804
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -4
                max                             4
            }
        }
        affector                                Scale Affector76
        {
            xyz_scale                           dyn_random
            {
                min                             -1
                max                             1
            }
        }
    }
}
