system rift/tower_antimatter_explosion
{
    fixed_timeout                               1
    nonvisible_update_timeout                   0.5
    scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 10
	
	technique lightning_small
    {
        visual_particle_quota                   25
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_bolt_4x4_blue_01
        renderer                                Billboard
        {
            render_queue_group                  65
            texture_coords_rows                 4
            texture_coords_columns              4
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       100
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            velocity                            0
			duration							0.8
            all_particle_dimensions             dyn_random
            {
                min                             25
                max                             50
            }
            position                            0 10 0
            end_texture_coords_range            3
            radius                              20
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.141304  0.498039 0.498039 0.498039 1
            time_colour                         1    0.498039 0.498039 0.498039 0
            colour_operation                    multiply
        }
        affector                                TextureRotator Affector18
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
    }
	
    technique firealpha2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/explosion_and_smoke_blue_anim
        renderer                                Billboard
        {
            render_queue_group                  62
            texture_coords_rows                 4
            texture_coords_columns              16
            billboard_rotation_type             vertex
        }
        emitter                                 Circle 
        {
            emission_rate                       50
            angle                               1
            time_to_live                        dyn_random
            {
                min                             1.5
                max                             2
            }
            velocity                            dyn_random
            {
                min                             30
                max                             60
            }
            all_particle_dimensions             dyn_random
            {
                min                             15
                max                             25
            }
            force_emission                      true
            radius                              5
        }
        affector                                Scale 
        {
            xyz_scale                           100
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -0.4
                max                             0.4
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
        affector                                TextureAnimator Affector18
        {
            end_texture_coords_range            63
            texture_start_random                false
        }
        affector                                Colour Affector68
        {
            time_colour                         0    0.501961 0.501961 0.501961 0.898039
            time_colour                         0.608696  0.121569 0.121569 0.121569 0.698039
            time_colour                         1    0.0666667 0.0666667 0.0666667 0
        }
    }
	
	technique sparks_ground
    {
        visual_particle_quota                   125
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks_ground
        {
            emission_rate                       250
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             40
                max                             80
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            position                            0 10 0
            start_colour_range                  0.501961 0 1 1
            end_colour_range                    1 0 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.11087  0.752941 0.752941 0.752941 1
            time_colour                         0.758696  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
	
    technique flash2
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lensflare_depth_off
        renderer                                Billboard
        {
            render_queue_group                  65
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.25
            velocity                            0
            all_particle_dimensions             50
            position                            0 75 0
            start_colour_range                  1 1 0.50196 1
            end_colour_range                    1 0.501961 0.25098 1
            colour                              1 0.501961 0 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           800
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.3  0.5 0.5 1 1
            time_colour                         0.5  0.5 0.5 1 1
            time_colour                         1    0 0 0 1
        }
    }
 
	
    technique ring
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_hit_circle_01
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.7
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           400
        }
        affector                                Colour 
        {
            time_colour                         0    0.5 0.5 1 1
            time_colour                         1    0 0 0 0
        }
    }
	
	technique ring_1
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_hit_circle_01
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.7
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           600
        }
        affector                                Colour 
        {
            time_colour                         0    0.5 0.5 1 1
            time_colour                         1    0 0 0 0
        }
    }
	
    technique sparks_ring
    {
        visual_particle_quota                   125
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Circle sparks_ground
        {
            emission_rate                       250
            angle                               1
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             0.7
            }
            velocity                            dyn_random
            {
                min                             300
                max                             350
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            position                            0 10 0
            start_colour_range                  0.501961 0 1 1
            end_colour_range                    1 0 1 1
            auto_direction                      true
            force_emission                      true
            radius                              1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.508696  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
	
	technique ring_2
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_hit_circle_01
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.7
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           800
        }
        affector                                Colour 
        {
            time_colour                         0    0.5 0.5 1 1
            time_colour                         1    0 0 0 0
        }
    }
}
