system rift/tower_morphium_emitter_dissolve
{
    fixed_timeout                               3
    nonvisible_update_timeout                   1
    scale_velocity                              0.02
    scale                                       0.02 0.02 0.02
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 5
    technique rings_alpha_2
    {
        visual_particle_quota                   80
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/alien_square_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Emitter7
        {
            angle                               0
            time_to_live                        1
            velocity                            1
            duration                            1
            all_particle_dimensions             150
            colour                              0.3 0.3 0.3 1
        }
        affector                                ScaleVelocity Affector308
        {
            velocity_scale                      1500
            since_start_system                  true
        }
        affector                                Colour Affector14
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
    }
    technique ball
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/flare_add_02
        renderer                                Billboard
        {
            render_queue_group                  60
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       20
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            all_particle_dimensions             1
            position                            0 50 0
            colour                              0.262745 0.937255 0.870588 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.501961 1 1 0
            time_colour                         0.504348  0.501961 1 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
        affector                                Scale Affector24
        {
            xyz_scale                           1500
        }
    }
    technique glow
    {
        keep_local                              true
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       100
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.6
            }
            velocity                            1
            all_particle_dimensions             dyn_random
            {
                min                             1
                max                             2
            }
            position                            0 50 0
            colour                              0.262745 0.937255 0.870588 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0.501961 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                TextureRotator Affector331
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -1
                max                             1
            }
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
        affector                                Scale Affector25
        {
            xyz_scale                           1500
        }
    }
	
	technique sparks_ground
    {
        visual_particle_quota                   125
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_blue_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks_ground
        {
            emission_rate                       300
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             1
                max                             150
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            position                            0 10 0
            start_colour_range                  0.501961 0 1 1
            end_colour_range                    1 0 1 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.11087  0.752941 0.752941 0.752941 1
            time_colour                         0.758696  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
	
    technique hex
    {
        visual_particle_quota                   50
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/hex
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks_ground
        {
            emission_rate                       250
            angle                               1
            time_to_live                        dyn_random
            {
                min                             2
                max                             3
            }
            velocity                            dyn_random
            {
                min                             10
                max                             40
            }
            all_particle_dimensions             dyn_random
            {
                min                             20
                max                             30
            }
            position                            0 150 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            force_emission                      true
            box_width                           75
            box_height                          300
            box_depth                           75
        }
        affector                                Colour 
        {
            time_colour                         0    0 0.501961 1 0
            time_colour                         0.502174  0 0.501961 1 0.247059
            time_colour                         1    0 0.501961 1 0
        }
    }
}
