system rift/cosmic_bradron_boss_shockwave
{
    fixed_timeout                               1.5
    nonvisible_update_timeout                   1
    scale_velocity                              0.05
    scale                                       0.05 0.05 0.05
    tight_bounding_box                          true
    fade_out                                    true
    cache_count                                 2
    technique flash2
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lensflare_depth_off
        renderer                                Billboard
        {
            render_queue_group                  65
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.25
            velocity                            0
            all_particle_dimensions             200
            position                            0 10 0
            start_colour_range                  1 1 0.50196 1
            end_colour_range                    1 0.501961 0.25098 1
            colour                              1 0.501961 0 1
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1000
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.3  0.953737 0 1 1
            time_colour                         0.5  0.953737 0 1 1
            time_colour                         1    0 0 0 1
        }
    }
    technique ring
    {
        visual_particle_quota                   2
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/mp_hit_circle_01
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point ring
        {
            time_to_live                        0.7
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale Affector20
        {
            xyz_scale                           1000
        }
        affector                                Colour 
        {
            time_colour                         0    0.953737 0 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique sparks_ground
    {
        visual_particle_quota                   125
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_violet_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Box sparks_ground
        {
            emission_rate                       250
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1
                max                             1.5
            }
            velocity                            dyn_random
            {
                min                             40
                max                             80
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            position                            0 50 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 0
            time_colour                         0.11087  0.752941 0.752941 0.752941 1
            time_colour                         0.758696  0.501961 0.501961 0.501961 1
            time_colour                         1    0 0 0 0
        }
    }
    technique sparks_ring
    {
        visual_particle_quota                   125
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_violet_01
        renderer                                Billboard
        {
            render_queue_group                  62
            billboard_rotation_type             vertex
        }
        emitter                                 Circle sparks_ground
        {
            emission_rate                       250
            angle                               1
            time_to_live                        dyn_random
            {
                min                             0.6
                max                             0.7
            }
            velocity                            dyn_random
            {
                min                             300
                max                             350
            }
            all_particle_dimensions             dyn_random
            {
                min                             2
                max                             3
            }
            position                            0 10 0
            start_colour_range                  1 0.501961 0 1
            end_colour_range                    1 1 0 1
            auto_direction                      true
            force_emission                      true
            radius                              1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.508696  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique refract
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/distortion_circle_02
        renderer                                Billboard
        {
            render_queue_group                  160
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            time_to_live                        0.7
            velocity                            0
            all_particle_dimensions             1
            position                            0 10 0
            force_emission                      true
        }
        affector                                Scale flash2
        {
            xyz_scale                           1000
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.502174  1 1 1 1
            time_colour                         1    0 0 0 0
        }
    }
    technique lightning_directional_0
    {
        visual_particle_quota                   100
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/lightning_atlas_01
        renderer                                Billboard
        {
            render_queue_group                  63
            texture_coords_rows                 2
            texture_coords_columns              2
            billboard_type                      oriented_self
            billboard_origin                    top_center
            billboard_rotation_type             vertex
        }
        emitter                                 Circle add_flame_blue
        {
            emission_rate                       100
            angle                               0
            time_to_live                        0.7
            velocity                            0.1
            particle_width                      10
            particle_height                     20
            position                            0 25 0
            keep_local                          true
            end_texture_coords_range            3
            colour                              0 1 1 1
            auto_direction                      true
            force_emission                      true
            radius                              1
        }
        affector                                TextureRotator Affector168
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3.3
                max                             -3.2
            }
            rotation_speed                      0
        }
        affector                                Colour Affector197
        {
            time_colour                         0    0.953737 0 1 1
            time_colour                         0.506522  0.953737 0 1 1
            time_colour                         1    0.953737 0 1 0
        }
        affector                                Scale Affector9
        {
            x_scale                             dyn_random
            {
                min                             250
                max                             500
            }
            y_scale                             dyn_random
            {
                min                             300
                max                             600
            }
        }
    }
    technique flash2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/spark_rectangle_violet_01
        renderer                                Billboard
        {
            render_queue_group                  65
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 SphereSurface flash2
        {
            emission_rate                       25
            time_to_live                        0.35
            velocity                            0
            all_particle_dimensions             50
            keep_local                          true
            colour                              0.776471 0.388235 0 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0.953737 0 1 1
            time_colour                         1    0 0 0 0
        }
        affector                                Scale Affector78
        {
            xyz_scale                           dyn_random
            {
                min                             150
                max                             200
            }
        }
        affector                                TextureRotator Affector128
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             0.2
                max                             0.4
            }
        }
    }
    technique flare2
    {
        visual_particle_quota                   5
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  61
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point flash2
        {
            emission_rate                       25
            time_to_live                        0.5
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             50
                max                             150
            }
            keep_local                          true
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.2  0.953737 0 1 1
            time_colour                         0.802174  1 0 0.875445 0.686275
            time_colour                         1    0 0 0 0
        }
        affector                                Scale Affector77
        {
            xyz_scale                           dyn_random
            {
                min                             100
                max                             200
            }
        }
    }
}
