system rift/cryo_laser_pointer
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.0125
    scale                                       0.0125 0.0125 0.0125
    tight_bounding_box                          true
    category                                    RIFT
    fade_out                                    true
    cache_count                                 4
    technique add_flame_blue
    {
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles/glow_add_02
        renderer                                Billboard
        {
            render_queue_group                  63
            billboard_rotation_type             vertex
            accurate_facing                     true
        }
        emitter                                 Box add_flame_blue
        {
            emission_rate                       3000
            angle                               0
            time_to_live                        0.1
            velocity                            1
            all_particle_dimensions             dyn_random
            {
                min                             10
                max                             30
            }
            position                            1500 0 0
            direction                           1 0 0
            colour                              0 0.47451 0 1
            box_width                           3000
            box_height                          1
            box_depth                           1
        }
    }
}
