system rift/plasma_staballizer_marker_circle
{
    keep_local                                  true
    nonvisible_update_timeout                   1
    scale_velocity                              0.03
    scale                                       0.03 0.03 0.02
    tight_bounding_box                          true
    cache_count                                 2
    technique ring_radius1
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   0
        emitted_technique_quota                 0
        emitted_affector_quota                  0
        emitted_system_quota                    0
        material                                particles_noatlas/alien_marker_ring_violet_01
        renderer                                Billboard
        {
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            emission_rate                       40
            angle                               0
            time_to_live                        360
            velocity                            0.0001
            all_particle_dimensions             60
            colour                              0.294118 0.294118 0.294118 1
        }
        affector                                TextureRotator Affector226
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      4
        }
    }
}
