GameplayResourceDef
{
	id				"ammo_tower_plasmoid_cells"
	localization_id "resource_name/ammo_tower_plasmoid_cells"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_plasmoid_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_plasmoid_cells_icon_bigger"
	base_storage	"300"
	production		"16"
	hud_visible 	"build_menu"
	order			"5"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_magmatic_cells"
	localization_id "resource_name/ammo_tower_magmatic_cells"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_magmatic_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_magmatic_cells_icon_bigger"
	base_storage	"300"
	production		"16"
	hud_visible 	"build_menu"
	order			"2"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_acidic_cells"
	localization_id "resource_name/ammo_tower_acidic_cells"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_acidic_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_acidic_cells_icon_bigger"
	base_storage	"300"
	production		"16"
	hud_visible 	"build_menu"
	order			"3"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_cryogenic_cells"
	localization_id "resource_name/ammo_tower_cryogenic_cells"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_cryogenic_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_cryogenic_cells_icon_bigger"
	base_storage	"300"
	production		"16"
	hud_visible 	"build_menu"
	order			"1"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_tower_cosmic_cells"
	localization_id "resource_name/ammo_tower_cosmic_cells"
	bp  			""
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/ammo_tower_cosmic_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_tower_cosmic_cells_icon_bigger"
	base_storage	"300"
	production		"16"
	hud_visible 	"build_menu"
	order			"4"
	
	
	manufacture_cost "1"
}

GameplayResourceDef
{
	id				"ammo_mech_cosmic_cells"
	localization_id "resource_name/ammo_mech_cosmic_cells"
	bp  			""
	type 			"ammo_mech"
	icon			"gui/hud/resource_icons/ammo_mech_cosmic_cells_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_cosmic_cells_icon_bigger"
	base_storage	"30"
	production		"30"
	hud_visible 	"never"
	order			"19"
	
	manufacture_cost "1"
}
