//////////////////////////////////// FAUNA ////////////////////////////////////////////////
GameplayResourceDef
{
	id				"specimen_cosmic_arachnoid_boss"
	localization_id "resource_name/specimen_cosmic_arachnoid_boss"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_arachnoid_sentinel_crystal"
	localization_id "resource_name/specimen_cosmic_arachnoid_sentinel_crystal"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_arachnoid_sentinel_crystal_alpha"
	localization_id "resource_name/specimen_cosmic_arachnoid_sentinel_crystal_alpha"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_morirot"
	localization_id "resource_name/specimen_cosmic_morirot"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_spawner_cosmic_morirot"
	localization_id "resource_name/specimen_spawner_cosmic_morirot"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_spawner_cosmic_kermon"
	localization_id "resource_name/specimen_spawner_cosmic_kermon"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_spawner_cosmic_canoptrix"
	localization_id "resource_name/specimen_spawner_cosmic_canoptrix"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_necrodon"
	localization_id "resource_name/specimen_cosmic_necrodon"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_bomogan"
	localization_id "resource_name/specimen_cosmic_bomogan"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_phirian"
	localization_id "resource_name/specimen_cosmic_phirian"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_gnerot"
	localization_id "resource_name/specimen_cosmic_gnerot"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_canoptrix_crystal"
	localization_id "resource_name/specimen_cosmic_canoptrix_crystal"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_canoptrix_crystal_alpha"
	localization_id "resource_name/specimen_cosmic_canoptrix_crystal_alpha"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_kafferroceros"
	localization_id "resource_name/specimen_cosmic_kafferroceros"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_kafferroceros_alpha"
	localization_id "resource_name/specimen_cosmic_kafferroceros_alpha"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_kermon"
	localization_id "resource_name/specimen_cosmic_kermon"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_hedroner"
	localization_id "resource_name/specimen_cosmic_hedroner"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_lesigian"
	localization_id "resource_name/specimen_cosmic_lesigian"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_baxmoth"
	localization_id "resource_name/specimen_cosmic_baxmoth"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_hedroner_boss"
	localization_id "resource_name/specimen_cosmic_hedroner_boss"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

//////////////////////////////////// OTHER ///////////////////////////////

GameplayResourceDef
{
	id				"specimen_alien_tower_artillery_cosmo"
	localization_id "resource_name/specimen_alien_tower_artillery_cosmo"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_alien_tower_artillery_cosmo_mkII"
	localization_id "resource_name/specimen_alien_tower_artillery_cosmo_mkII"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

//////////////////////////////////// FLORA ///////////////////////////////

GameplayResourceDef
{
	id				"specimen_cosmic_crystal_creeper"
	localization_id "resource_name/specimen_cosmic_crystal_creeper"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}

GameplayResourceDef
{
	id				"specimen_cosmic_crystal"
	localization_id "resource_name/specimen_cosmic_crystal"
	bp  			""
	type 			"loot"
	specific_type	"specimen"
	icon			"gui/hud/resource_icons/specimen"
	bigger_icon		"gui/hud/resource_icons/specimen_bigger"
	hud_visible 	"never"
	allow_overflow 	"1"
}
